### ISSUE TITLE
"failed to send metric metadata to datadog" on samples

### ISSUE THREAD

**Issue by juan-f** [micrometer-metrics/micrometer#1035]
Using the following example of your repo sample: https://github.com/micrometer-metrics/micrometer-samples-spring-boot-datadog

But I am getting the following error: 

```
2018-11-27 13:28:50.566  WARN 22056 --- [trics-publisher] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata to datadog

java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_151]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_151]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_151]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_151]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_151]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[na:1.8.0_151]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_151]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_151]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_151]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_151]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_151]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_151]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[na:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[na:1.8.0_151]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) ~[na:1.8.0_151]
	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:55) ~[micrometer-core-1.1.0.jar:1.1.0]
	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:284) ~[micrometer-core-1.1.0.jar:1.1.0]
	at io.micrometer.datadog.DatadogMeterRegistry.postMetricMetadata(DatadogMeterRegistry.java:259) ~[micrometer-registry-datadog-1.1.0.jar:1.1.0]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[na:1.8.0_151]
	at io.micrometer.datadog.DatadogMeterRegistry.publish(DatadogMeterRegistry.java:142) ~[micrometer-registry-datadog-1.1.0.jar:1.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

Doing a curl POST to https://app.datadoghq.com/api/v1/series?api_key=xxxxxxxxxxxxx works ok ({"status": "ok"})

Any help will be greatly appreciated

**Comment by juan-f** [comment]
Solved. It was a proxy issue on the service side

**Comment by mglebka** [comment]
@juan-f , @jkschneider , hello guys, could you please let me know if there is any configuration where I can specify my proxy ? I'm interested in defining it using [DatadogProperties](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/datadog/DatadogProperties.java)

**Comment by izeye** [comment]
@mglebka Yes, you can as described in the Javadoc on the `DatadogProperties.uri`.

See https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/autoconfigure/export/datadog/DatadogProperties.java#L51-L55

If you're using Spring Boot, you can use the following property:

```
management.metrics.export.datadog.uri=https://app.datadoghq.com # URI to ship metrics to. If you need to publish metrics to an internal proxy en-route to Datadog, you can define the location of the proxy with this.
```

**Comment by randysecrist** [comment]
Any thoughts on ... adding a retry property to StepRegistryProperties so the push can be retried "n" times before failing?

**Comment by randysecrist** [comment]
in our env, this has started to happen since Feb 26 - and it has happened 33 times.  Any thought on adding a retry property to StepRegistryProperties ; such that the push will try "n" times before giving up?

**Comment by shakuzen** [comment]
> in our env, this has started to happen

@randysecrist What exactly is happening? A push to Datadog is failing with `java.net.SocketTimeoutException: connect timed out` intermittently? Do subsequent pushes also fail?

**Comment by randysecrist** [comment]
correct.  connect timed out are logged ; subsequent pushes succeed.  I'm not sure if we are losing metric for those logged failures or if they are just queued up to be pushed on the next successful push?

**Comment by izeye** [comment]
@randysecrist There's no out-of-the-box support for retry. You can use Resilience4j for it and [this sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/datadog-resilience4j) shows how to do it.

See also https://github.com/micrometer-metrics/micrometer-docs/pull/85
