### ISSUE TITLE
[BUG] Counter object is not removed from Dropwizard registry

### ISSUE THREAD

**Issue by mrniko** [micrometer-metrics/micrometer#1038]
Follow code throws `java.lang.IllegalArgumentException: A metric named test already exists` exception. Meter is not removed from Dropwizard registry, only from micrometer registry. Reproducible with Dropwizard 4.0.3 and micrometer 1.1.0.

Code to reproduce the case:
```java
        DropwizardConfig consoleConfig = new DropwizardConfig() {
            @Override
            public String prefix() {
                return "console";
            }
            @Override
            public String get(String key) {
                return null;
            }
        };

        MetricRegistry reg = new MetricRegistry();
        DropwizardMeterRegistry registry = new DropwizardMeterRegistry(consoleConfig, reg, HierarchicalNameMapper.DEFAULT, Clock.SYSTEM) {
            @Override
            protected Double nullGaugeValue() {
                return null;
            }
        };
        
        Counter counter = registry.counter("test");
        registry.remove(counter);
        registry.counter("test");
```

Exception:

```java
java.lang.IllegalArgumentException: A metric named test already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:97)
	at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.newCounter(DropwizardMeterRegistry.java:60)
	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:528)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:580)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:543)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:528)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:245)
	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:128)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:352)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:363)
```

**Comment by izeye** [comment]
@mrniko Thanks for the report and the test! I created #1040 to try to fix it.
