### ISSUE TITLE
Elastic indexing counters/timers can fail due to different numeric types

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#1071]
See https://github.com/micrometer-metrics/micrometer/issues/498#issuecomment-446816808

**Comment by izeye** [comment]
In Elasticsearch 6.7.2 (the latest 6.x version ATM), a floating point number (`count`) in JSON is typed as `float` as follows:

```
$ curl -XDELETE http://localhost:9200/metrics-2019-05
{"acknowledged":true}
$ curl -XPOST --header "Content-Type: application/json" http://localhost:9200/metrics-2019-05/doc/_bulk --data-binary '
> { "index" : {} }
> {"@timestamp":"2019-05-14T15:31:46.313Z","name":"jvm_gc_memory_promoted","type":"counter","count":0.0}
> '
{"took":105,"errors":false,"items":[{"index":{"_index":"metrics-2019-05","_type":"doc","_id":"l7_-tmoBVqC16kvPmpLF","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
$ curl http://localhost:9200/metrics-2019-05/_mapping?pretty
{
  "metrics-2019-05" : {
    "mappings" : {
      "doc" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "count" : {
            "type" : "float"
          },
          "name" : {
            "type" : "keyword"
          },
          "type" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      },
      "_default_" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "name" : {
            "type" : "keyword"
          }
        }
      }
    }
  }
}
$
```

An integer number (`count`) in JSON is typed as `long` as follows:

```
$ curl -XDELETE http://localhost:9200/metrics-2019-05
{"acknowledged":true}
$ curl -XPOST --header "Content-Type: application/json" http://localhost:9200/metrics-2019-05/doc/_bulk --data-binary '
> { "index" : {} }
> {"@timestamp":"2019-05-14T15:31:46.313Z","name":"jvm_gc_pause","type":"timer","action":"end of major GC","cause":"Metadata GC Threshold","count":0,"sum":0.0,"mean":0.0,"max":0.0}
> '
{"took":113,"errors":false,"items":[{"index":{"_index":"metrics-2019-05","_type":"doc","_id":"mL__tmoBVqC16kvPR5LB","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}
$ curl http://localhost:9200/metrics-2019-05/_mapping?pretty
{
  "metrics-2019-05" : {
    "mappings" : {
      "doc" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "action" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "cause" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "count" : {
            "type" : "long"
          },
          "max" : {
            "type" : "float"
          },
          "mean" : {
            "type" : "float"
          },
          "name" : {
            "type" : "keyword"
          },
          "sum" : {
            "type" : "float"
          },
          "type" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      },
      "_default_" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "name" : {
            "type" : "keyword"
          }
        }
      }
    }
  }
}
$ 
```

Mixing the two ends up with `float` as follows:

```
$ curl -XDELETE http://localhost:9200/metrics-2019-05
{"acknowledged":true}
$ curl -XPOST --header "Content-Type: application/json" http://localhost:9200/metrics-2019-05/doc/_bulk --data-binary '
> { "index" : {} }
> {"@timestamp":"2019-05-14T15:31:46.313Z","name":"jvm_gc_memory_promoted","type":"counter","count":0.0}
> { "index" : {} }
> {"@timestamp":"2019-05-14T15:31:46.313Z","name":"jvm_gc_pause","type":"timer","action":"end of major GC","cause":"Metadata GC Threshold","count":0,"sum":0.0,"mean":0.0,"max":0.0}
> '
{"took":88,"errors":true,"items":[{"index":{"_index":"metrics-2019-05","_type":"doc","_id":"n78Ct2oBVqC16kvPAJJ4","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}},{"index":{"_index":"metrics-2019-05","_type":"doc","_id":"oL8Ct2oBVqC16kvPAJJ4","status":400,"error":{"type":"illegal_argument_exception","reason":"mapper [count] cannot be changed from type [float] to [long]"}}}]}
$ curl http://localhost:9200/metrics-2019-05/_mapping?pretty
{
  "metrics-2019-05" : {
    "mappings" : {
      "doc" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "count" : {
            "type" : "float"
          },
          "name" : {
            "type" : "keyword"
          },
          "type" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      },
      "_default_" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "name" : {
            "type" : "keyword"
          }
        }
      }
    }
  }
}
$
```

But a type conversion error occurs occasionally. In Elasticsearch, the following exceptions are thrown:

```
[2019-05-15T00:42:02,888][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [AgISpaH] failed to put mappings on indices [[[metrics-2019-05/MyHvhd4ORYSGZBKK1zgDUA]]], type [doc]
java.lang.IllegalArgumentException: mapper [count] cannot be changed from type [float] to [long]
	at org.elasticsearch.index.mapper.MappedFieldType.checkTypeName(MappedFieldType.java:145) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MappedFieldType.checkCompatibility(MappedFieldType.java:158) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.FieldTypeLookup.validateField(FieldTypeLookup.java:157) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:108) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:494) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:403) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:338) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:330) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:231) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:200) [elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:135) [elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-6.7.2.jar:6.7.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[2019-05-15T00:42:02,889][DEBUG][o.e.a.b.TransportShardBulkAction] [AgISpaH] [metrics-2019-05][2] failed to execute bulk item (index) index {[metrics-2019-05][doc][oL8Ct2oBVqC16kvPAJJ4], source[{"@timestamp":"2019-05-14T15:31:46.313Z","name":"jvm_gc_pause","type":"timer","action":"end of major GC","cause":"Metadata GC Threshold","count":0,"sum":0.0,"mean":0.0,"max":0.0}]}
java.lang.IllegalArgumentException: mapper [count] cannot be changed from type [float] to [long]
	at org.elasticsearch.index.mapper.MappedFieldType.checkTypeName(MappedFieldType.java:145) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MappedFieldType.checkCompatibility(MappedFieldType.java:158) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.FieldTypeLookup.validateField(FieldTypeLookup.java:157) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:108) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:494) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:403) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:338) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:330) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:231) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:200) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:135) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-6.7.2.jar:6.7.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-6.7.2.jar:6.7.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

The order of the two doesn't matter to reproduce this and it doesn't happen consistently, so I suspect there's some race condition in Elasticsearch.

Regardless of the Elasticsearch issue, I think this issue can be avoided by using `double` consistently. This aligns with Micrometer internal types.

#1420 might have the same root cause.
