### ISSUE TITLE
Metrics sent intermittently to datadog

### ISSUE THREAD

**Issue by subrasel** [micrometer-metrics/micrometer#1481]
We are using spring boot 1.5 and we have custom metrics sent to datadog using micrometer. Though this worked fine in all environment when we put it in production we got error "failed to send metrics: Payload too big". For this we looked at the issue https://github.com/micrometer-metrics/micrometer/issues/1250 and added the batch size. 

After adding batch size it started sending metrics but after 2 hours it stopped and again started sending metrics 15 hours later. What could be the issue?  Any suggestion will be helpful

**Comment by subrasel** [comment]
More details from the above issue

Code Snippet
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Counter;


@Inject
private MeterRegistry meterRegistry;
String[] tags = {"tag1key", "tag1value"};
Counter c = Counter.builder("some-key").description("").tags(tags).register(meterRegistry);
c.increment(1);
c.close();
 
We are seeing these errors in thread dump report.. 

"dd-span-cleaner" #40 daemon prio=5 os_prio=0 tid=0x00007f7ab2811000 nid=0x18ed waiting on condition [0x00007f7ab5e48000]
   java.lang.Thread.State: TIMED_WAITING (parking)
                at sun.misc.Unsafe.park(Native Method)
                - parking to wait for  <0x00000007595023f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
                at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
                at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
                - None




"dd-agent-writer" #10 daemon prio=5 os_prio=0 tid=0x00007f7ac4010000 nid=0x18ab waiting on condition [0x00007f7ad98e5000]
   java.lang.Thread.State: WAITING (parking)
                at sun.misc.Unsafe.park(Native Method)
                - parking to wait for  <0x000000075827ad58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
                at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
                - None

"dd-agent-writer" #8 daemon prio=5 os_prio=0 tid=0x00007f7b19802800 nid=0x18aa waiting on condition [0x00007f7ad99e6000]
   java.lang.Thread.State: TIMED_WAITING (parking)
                at sun.misc.Unsafe.park(Native Method)
                - parking to wait for  <0x00000007591e3420> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
                at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
                at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
                at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
                at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
                - None

**Comment by shakuzen** [comment]
If you have a lot of tags or long tag names/values, then the payload size will increase per metric, which might be putting you over the payload size limit Datadog enforces. Those thread names look related to the Datadog agent, not Micrometer.
