### ISSUE TITLE
connection time out in sending metrics to datadog

### ISSUE THREAD

**Issue by pchatsu** [micrometer-metrics/micrometer#1499]
We use io.micrometer:micrometer-core:1.1.0 with spring boot actuator.
We have sometimes failed to send metrics to datadog during running application.

[Log]
message: failed to send metrics to datadog
module: i.m.d.DatadogMeterRegistry
line: 146 
exception:  java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)

Any ideas?

**Comment by izeye** [comment]
@pchatsu Thanks for the report but it seems to be "connect timed out" from JDK, so there’s nothing Micrometer can do for it. You can tweak connect timeout configuration to fit your environment if it helps.

**Comment by shakuzen** [comment]
It sounds like your application may not be able to connect quickly to the Datadog API. The `connectTimeout` can be configured with the `HttpSender` used with the `DatadogMeterRegistry`. For now, it can also be configured with the `connectTimeout` method on the Config class - it defaults to 1 second.

**Comment by pchatsu** [comment]
@izeye @shakuzen thanks for your advice! I'll try to configure `connectTimeout`.

**Comment by shakuzen** [comment]
> thanks for your advice! I'll try to configure `connectTimeout`.

Let us know if that worked for you. I'll close this for now and we can reopen it if there are some changes necessary in Micrometer.

**Comment by OndraZizka** [comment]
Micrometer can provide a way to suppress these not too useful messages. For instance, Datadog's servers tend to be flaky, and `connection timeout` does not help as the particular request got unlucky and hit a dying node.

The stacktrace starts with:
```
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:?]
	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98) ~[us-http-api.jar:?]
	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:306) ~[us-http-api.jar:?]
	at io.micrometer.datadog.DatadogMeterRegistry.publish(DatadogMeterRegistry.java:145) ~[us-http-api.jar:?]
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54) ~[us-http-api.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

My suggestion is, to catch exceptions, and allow to react to the exceptions with own handler.

```kotlin
override fun connectTimeoutHandler() = { ex -> log.debug { ex.msg } }
```
