### ISSUE TITLE
Micrometer with ehcache and datadog throws InvocationTargetException

### ISSUE THREAD

**Issue by cscheffel** [micrometer-metrics/micrometer#1543]
We have integrated micormeter in a spring boot 2.1.6-App which use ehcache 2.10.6 as caching provider. The runtime enviroment is open jdk 11. After adding micrometer 1.1.5 (and as a try 1.2.0) and a custom specifc counter everything works well at the beginning. 

Micrometer transfers the custom counter to datadog.

After a view seconds (i.e. timerbased), micrometer trys to transmit metering data for ehcache which results into a InvocationTargetException. At this moment, all transmitting is stopped. Even the custom counter is not transmitted any more.

Stacktrace:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:65)
        at net.sf.ehcache.statistics.extended.AbstractStatistic.value(AbstractStatistic.java:57)
        at net.sf.ehcache.statistics.extended.SemiExpiringStatistic.value(SemiExpiringStatistic.java:33)
        at net.sf.ehcache.statistics.StatisticsGateway.getLocalHeapSizeInBytes(StatisticsGateway.java:327)
        at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:40)
        at io.micrometer.core.instrument.Measurement.getValue(Measurement.java:39)
        at io.micrometer.datadog.DatadogMeterRegistry.lambda$writeMeter$12(DatadogMeterRegistry.java:210)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4745)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4753)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1510)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.micrometer.datadog.DatadogMeterRegistry.publish(DatadogMeterRegistry.java:134)
        at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.terracotta.statistics.StatisticsManager$MethodCallable.call(StatisticsManager.java:113)
        at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:63)
        ... 30 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field jdk.internal.ref.PhantomCleanable jdk.internal.ref.PhantomCleanable.prev accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @5f80fa43
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
        at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getAllFields(ObjectGraphWalker.java:271)
        at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getFilteredFields(ObjectGraphWalker.java:229)
        at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.walk(ObjectGraphWalker.java:160)
        at net.sf.ehcache.pool.sizeof.SizeOf.deepSizeOf(SizeOf.java:72)
        at net.sf.ehcache.pool.impl.DefaultSizeOfEngine.sizeOf(DefaultSizeOfEngine.java:190)
        at net.sf.ehcache.store.cachingtier.OnHeapCachingTier.getInMemorySizeInBytes(OnHeapCachingTier.java:265)
        ... 35 common frames omitted
```

**Comment by shakuzen** [comment]
Is ehcache 2.10.6 compatible with Java 11?

**Comment by cscheffel** [comment]
As far as I know, it is. We use it as the Version, which is referenced by Spring Boot 2.1.6 (via bom) and use it with java 11 and without any problems since 4 month.

The documentation says: java >= 8

**Comment by shakuzen** [comment]
I'm having trouble reproducing this. Could you provide a minimal sample project with steps to reproduce this? I'm getting a similar warning (below), but it does not cause any exception.

```
WARNING: Illegal reflective access by net.sf.ehcache.pool.sizeof.ObjectGraphWalker (file:/Users/tludwig/.m2/repository/net/sf/ehcache/ehcache/2.10.6/ehcache-2.10.6.jar) to field java.lang.String.value
```

**Comment by cscheffel** [comment]
I have seen this warning as well. After a while, transimission stopped.

I will try to create a demo project. 
Which Version of micrometer did you use? 1.1.5, 1.2.0 or latest?

**Comment by shakuzen** [comment]
> Which Version of micrometer did you use? 1.1.5, 1.2.0 or latest?

I used 1.2.0

**Comment by cscheffel** [comment]
I have build a small demo app: [https://github.com/cscheffel/demo-micrometer-ehcache](https://github.com/cscheffel/demo-micrometer-ehcache)

If you checkout, build (mvn package) and start this, it is a typical web hello world. Calling localhost:8080 shows a starting page and uses ehcache as cache. I you are interessted, i can send you a prebuild jar.

In this implementation, I was not able to reproduce the timed error, but if - after calling the web page one or serveral time - shut down the application, it throws the exception described above because mircometer tries to transmit the ehcache monitoring data to datadog.

Info: There is a datadog counter inside the app, which will fail to transmit, because I use a fake api-key. This is not the error we look for.

**Comment by shakuzen** [comment]
The exception on shutdown is different. It happens because the cache is already shutdown when it is trying to publish the metrics on application shutdown. We could probably handle that better, but it is a separate issue.

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:65) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.statistics.extended.AbstractStatistic.value(AbstractStatistic.java:57) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.statistics.extended.SemiExpiringStatistic.value(SemiExpiringStatistic.java:33) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.statistics.StatisticsGateway.getSize(StatisticsGateway.java:367) ~[ehcache-2.10.6.jar:2.10.6]
	at io.micrometer.core.instrument.binder.cache.EhCache2Metrics.size(EhCache2Metrics.java:67) ~[micrometer-core-1.2.0.jar:1.2.0]
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.lambda$bindTo$0(CacheMeterBinder.java:52) ~[micrometer-core-1.2.0.jar:1.2.0]
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:40) ~[micrometer-core-1.2.0.jar:1.2.0]
	at io.micrometer.core.instrument.Measurement.getValue(Measurement.java:39) ~[micrometer-core-1.2.0.jar:1.2.0]
	at io.micrometer.datadog.DatadogMeterRegistry.lambda$writeMeter$12(DatadogMeterRegistry.java:210) ~[micrometer-registry-datadog-1.2.0.jar:1.2.0]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4745) ~[na:na]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4753) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[na:na]
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at io.micrometer.datadog.DatadogMeterRegistry.publish(DatadogMeterRegistry.java:134) ~[micrometer-registry-datadog-1.2.0.jar:1.2.0]
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48) ~[micrometer-core-1.2.0.jar:1.2.0]
	at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:83) ~[micrometer-core-1.2.0.jar:1.2.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1036) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1029) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.terracotta.statistics.StatisticsManager$MethodCallable.call(StatisticsManager.java:113) ~[ehcache-2.10.6.jar:2.10.6]
	at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:63) ~[ehcache-2.10.6.jar:2.10.6]
	... 41 common frames omitted
Caused by: java.lang.IllegalStateException: The attribute Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4104) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2792) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.Cache.getSize(Cache.java:2689) ~[ehcache-2.10.6.jar:2.10.6]
	... 47 common frames omitted
```

**Comment by izeye** [comment]
I could reproduce this with [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-1543) if `--illegal-access=deny` VM option has been set. The stack trace wasn't the same but similar as follows:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:65) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.statistics.extended.AbstractStatistic.value(AbstractStatistic.java:57) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.statistics.extended.SemiExpiringStatistic.value(SemiExpiringStatistic.java:33) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.statistics.StatisticsGateway.getLocalHeapSizeInBytes(StatisticsGateway.java:327) ~[ehcache-2.10.6.jar:2.10.6]
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:40) ~[micrometer-core-1.1.6.jar:1.1.6]
	at io.micrometer.core.instrument.Measurement.getValue(Measurement.java:39) ~[micrometer-core-1.1.6.jar:1.1.6]
	at io.micrometer.datadog.DatadogMeterRegistry.lambda$writeMeter$12(DatadogMeterRegistry.java:210) ~[micrometer-registry-datadog-1.1.6.jar:1.1.6]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4745) ~[na:na]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4753) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[na:na]
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at io.micrometer.datadog.DatadogMeterRegistry.publish(DatadogMeterRegistry.java:134) ~[micrometer-registry-datadog-1.1.6.jar:1.1.6]
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48) ~[micrometer-core-1.1.6.jar:1.1.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.terracotta.statistics.StatisticsManager$MethodCallable.call(StatisticsManager.java:113) ~[ehcache-2.10.6.jar:2.10.6]
	at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:63) ~[ehcache-2.10.6.jar:2.10.6]
	... 30 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.LinkedHashMap$Entry java.util.LinkedHashMap.head accessible: module java.base does not "opens java.util" to unnamed module @531b35b4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170) ~[na:na]
	at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getAllFields(ObjectGraphWalker.java:271) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getFilteredFields(ObjectGraphWalker.java:229) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.walk(ObjectGraphWalker.java:160) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.pool.sizeof.SizeOf.deepSizeOf(SizeOf.java:72) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.pool.impl.DefaultSizeOfEngine.sizeOf(DefaultSizeOfEngine.java:190) ~[ehcache-2.10.6.jar:2.10.6]
	at net.sf.ehcache.store.MemoryStore.getInMemorySizeInBytes(MemoryStore.java:802) ~[ehcache-2.10.6.jar:2.10.6]
	... 36 common frames omitted
```

@cscheffel Could you confirm that `--illegal-access=deny` VM option has been used when the exception was thrown? If not, could you share how to run your application including VM options?

**Comment by cscheffel** [comment]
I did not set the --illegal-acces explicitly, but I will check this in my running environment.

What I have done is an implementation similar to #1582 in the DatadogMeterRegistry. This catches all exceptions while getting the value. This solved my problem and transmission does not stop anymore.

I think, it is a good idea to catch the errors at this point.

I could offer a pull request if interessted

**Comment by cscheffel** [comment]
Sorry for closing. I hit the wrong button

**Comment by zachariahyoung** [comment]
Not sure if this helps but I'm getting a similar error.  

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.ehcache.pool.sizeof.ObjectGraphWalker (jar:file:/jbh/ws_infrastructure_rules.jar!/BOOT-INF/lib/ehcache-2.10.6.jar!/) to field java.util.ArrayList.elementData
WARNING: Please consider reporting this to the maintainers of net.sf.ehcache.pool.sizeof.ObjectGraphWalker
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2019-09-10 13:21:11,378] [ERROR] [elastic-3] [o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler] [traceId=4db81dc143acceda, spanId=4db81dc143acceda, spanExportable=false, X-Span-Export=false, X-B3-SpanId=4db81dc143acceda, X-B3-TraceId=4db81dc143acceda] : [4d0202cf] 500 Server Error for HTTP GET "/ws_infrastructure_rules/prometheus"
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:65)
        at net.sf.ehcache.statistics.extended.AbstractStatistic.value(AbstractStatistic.java:57)
        at net.sf.ehcache.statistics.extended.SemiExpiringStatistic.value(SemiExpiringStatistic.java:33)
        at net.sf.ehcache.statistics.StatisticsGateway.getLocalHeapSizeInBytes(StatisticsGateway.java:327)
        at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:40)
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$3(PrometheusMeterRegistry.java:235)
        at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:69)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
        at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(PrometheusScrapeEndpoint.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
        at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
        at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
        at org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ElasticSchedulerInvoker.invoke(AbstractWebFluxEndpointHandlerMapping.java:233)
        at org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ElasticSchedulerInvoker.lambda$null$0(AbstractWebFluxEndpointHandlerMapping.java:228)
        at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:292)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
        at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.terracotta.statistics.StatisticsManager$MethodCallable.call(StatisticsManager.java:113)
        at org.terracotta.statistics.PassThroughStatistic.value(PassThroughStatistic.java:63)
        ... 29 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object jdk.internal.loader.AbstractClassLoaderValue$Sub.key accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @59532566
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
        at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getAllFields(ObjectGraphWalker.java:271)
        at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getFilteredFields(ObjectGraphWalker.java:229)
        at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.walk(ObjectGraphWalker.java:160)
        at net.sf.ehcache.pool.sizeof.SizeOf.deepSizeOf(SizeOf.java:72)
        at net.sf.ehcache.pool.impl.DefaultSizeOfEngine.sizeOf(DefaultSizeOfEngine.java:190)
        at net.sf.ehcache.store.MemoryStore.getInMemorySizeInBytes(MemoryStore.java:802)
        ... 35 common frames omitted`

**Comment by zachariahyoung** [comment]
Any workarounds for this issue?  Would ehcache 3 fix this?

**Comment by cscheffel** [comment]
If you use the changes in the pull request referenced above, it should be fixed. We tried it in production and have no drops anymore (except that we have events from ehcache which causes the fail).
Of course it would be better to fix the source error, but for mircometer it should be (imho) a good idea to not distrub other transmission if one event source fails.

**Comment by zachariahyoung** [comment]
@cscheffel I'm not using Datadog in my case.

**Comment by shakuzen** [comment]
Things should be better in that publishing does not stop and other meters are published even if one gauge function fails, thanks to #1582. As for the underlying cause, I think that will need to be reported to the EhCache folks to investigate. Let me know if this is still an issue on the latest patch versions and there is some change remaining to make in Micrometer.
