### ISSUE TITLE
CloudWatchMeterRegistry: error sending metric data

### ISSUE THREAD

**Issue by abendt-mhp** [micrometer-metrics/micrometer#1596]
we are using micrometer-registry-cloudwatch to write metrics from a spring boot application running in ECS/Fargate to AWS Cloudwatch.

we regularely have these errors in the log:
```
logger io.micrometer.cloudwatch.CloudWatchMeterRegistry
message error sending metric data

exception
com.amazonaws.services.cloudwatch.model.InvalidParameterValueException: The collection MetricData must not have a size greater than 20. (Service: AmazonCloudWatch; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 87ec1519-9c13-440e-8e70-b1d7eb71bcdf)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1660)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1324)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:1631)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:1600)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:1589)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:1494)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchAsyncClient$16.call(AmazonCloudWatchAsyncClient.java:840)
at com.amazonaws.services.cloudwatch.AmazonCloudWatchAsyncClient$16.call(AmazonCloudWatchAsyncClient.java:834)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
``` 

we have set the batchsize using spring boot options:
* _management.metrics.export.cloudwatch.batchSize_
* we tried some values <= 20 

due to our setup we cannot directly debug in AWS. When trying to reproduce the issue locally it looks that the batchSize is actually respected when sending the request (https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java#L110). Still the exception is occuring.

Let me know if we can provide any more information.

**Comment by shakuzen** [comment]
From the information you've provided, it looks likely the issue is caused by us batching by Micrometer `Meter`s but each `Meter` can translate to multiple `MetricData`, so a batch of 20 Meters might be more than 20 MetricData.

**Comment by nylund** [comment]
This is potentially caused by this PR https://github.com/micrometer-metrics/micrometer/pull/1504

**Comment by izeye** [comment]
Sorry for the trouble. I created #1612 to resolve this. The milestone needs to be changed to 1.2.2 or later as this was a regression which has been introduced in 1.2.1 due to #1504.
