### ISSUE TITLE
Incompatible with prometheus 1.0.0

### ISSUE THREAD

**Issue by Shahbazakhter** [micrometer-metrics/micrometer#1655]
Hello,
When we switch prometheus from 0.9.1 to 1.0.0, we are getting below error in applog.

All works ok with 0.9.1. 

Also in 1.0.0 i see metrics are getting pushed to the server but we still get below error.

Any incompatible issue with latest version?

```
2019-10-22 15:15:08,644 [*****][PrometheusPushGatewayManager.PushGatewayTaskScheduler-1][][][][][][][][][][][][] ERROR org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager - Unable to push metrics to Prometheus Pushgateway
java.io.IOException: Response code from http://localhost:9091/metrics/job/PIN-Metrics was 200
	at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:304)
	at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:178)
	at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push(PrometheusPushGatewayManager.java:108)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
<dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_pushgateway</artifactId>
 </dependency>
```

Thanks & Regards,
Shahbaz Akhter

**Comment by izeye** [comment]
@Shahbazakhter Thanks for the report, but it doesn't seem to relate to Micrometer as there's no code shown in the provided stack trace. Having said that, with a quick search, it seems to be related to https://github.com/prometheus/pushgateway/issues/301 and fixed in https://github.com/prometheus/client_java/pull/507 although there's no available version for it yet.

**Comment by Shahbazakhter** [comment]
@izeye Thanks for pointing me to the correct issue 👍

**Comment by izeye** [comment]
@Shahbazakhter Thanks for the quick confirmation! Closing.
