### ISSUE TITLE
Long running task timer throws exception on cast from Integer to Long

### ISSUE THREAD

**Issue by wvoelkl** [micrometer-metrics/micrometer#1690]
Env:
Spring Boot 1.5.4
Micrometer 1.2.0

```java
return LongTaskTimer
              .builder(MODEL_SYNC_METRIC_NAME)
              .tags(THREAD_NAME_KEY,
                      Thread.currentThread().getName(),
                      DIRECTION_KEY,
                      SYNC_DIRECTION,
                      MODEL_KEY,
                      this.modelClass.getSimpleName())
              .register(meterRegistry);
```
After the program runs for a bit when trying to send my first long running metric I get the following exception.
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
      at io.micrometer.signalfx.SignalFxMeterRegistry.addDatapoint(SignalFxMeterRegistry.java:154)
      at io.micrometer.signalfx.SignalFxMeterRegistry.addLongTaskTimer(SignalFxMeterRegistry.java:177)
```
Using the regular timer works as expected.

**Comment by izeye** [comment]
@wvoelkl Thanks for the report! I created https://github.com/micrometer-metrics/micrometer/pull/1691 to resolve this.
