### ISSUE TITLE
Support naming change of TimedExecutorService stats.

### ISSUE THREAD

**Issue by kazuki-ma** [micrometer-metrics/micrometer#1725]
We love `ExecutorServiceMetrics.monitor`, that's great.

But because of `ExecutorServiceMetrics.monitor` is famous and some library uses it internally, tag naming rule is conflict.

Our: 
===
```java
ExecutorServiceMetrics.monitor(
    Metrics.globalRegistry, 
    originalExecutor,
    jobName,
    Tag.of("ownerClass", getClass().getName()));
```

Library
====
```java
ExecutorServiceMetrics.monitor(
    Metrics.globalRegistry, 
    originalExecutor,
    jobName);
```

That happens 

```
Caused by: java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'executor_seconds' containing tag keys [ownerClass, name]. The meter you are attempting to register has keys [name].

	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:372)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:359)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:165)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:270)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:575)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:528)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:268)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:464)
	at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:140)
	at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:31)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.updateDescendants(CompositeMeterRegistry.java:216)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$add$5(CompositeMeterRegistry.java:141)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.add(CompositeMeterRegistry.java:133)
	at io.micrometer.core.instrument.Metrics.addRegistry(Metrics.java:44)
```

I think customize naming rule of Micrometer's in our side resolve this issue.
How do you think.

**Comment by kazuki-ma** [comment]
Aha, sorry I found `MeterFilter` and I'll use it to rename our executor stats.
Thank you.
