### ISSUE TITLE
IllegalArgumentException in JCacheMetrics.lookupStatistic

### ISSUE THREAD

**Issue by agliznetsov** [micrometer-metrics/micrometer#1797]
I get this exception when running spring boot application with apache ignite cache. The problem is that lookupStatistic method does not check if objectName is null.

```
09:15:56.510 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration': Invocation of init method failed; nested exception is javax.management.RuntimeOperationsException: Exception occurred trying to invoke the getter on the MBean
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.collibra.dgc.web.WebApp.main(WebApp.java:37)
Caused by: javax.management.RuntimeOperationsException: Exception occurred trying to invoke the getter on the MBean
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:624)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at io.micrometer.core.instrument.binder.cache.JCacheMetrics.lookupStatistic(JCacheMetrics.java:136)
	at io.micrometer.core.instrument.binder.cache.JCacheMetrics.missCount(JCacheMetrics.java:108)
	at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.bindTo(CacheMeterBinder.java:61)
	at org.springframework.boot.actuate.metrics.cache.CacheMetricsRegistrar.bindCacheToRegistry(CacheMetricsRegistrar.java:65)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.bindCacheToRegistry(CacheMetricsRegistrarConfiguration.java:78)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.lambda$bindCacheManagerToRegistry$0(CacheMetricsRegistrarConfiguration.java:73)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.bindCacheManagerToRegistry(CacheMetricsRegistrarConfiguration.java:73)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.boot.actuate.autoconfigure.metrics.cache.CacheMetricsRegistrarConfiguration.bindCachesToRegistry(CacheMetricsRegistrarConfiguration.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: Object name cannot be null
	... 38 common frames omitted
```

**Comment by shakuzen** [comment]
Could you please share what versions of Spring Boot and Micrometer you are using? If not the latest versions, could you check with the latest versions?

**Comment by agliznetsov** [comment]
spring-boot: 2.1.9.RELEASE
micrometer-core: 1.1.7

**Comment by shakuzen** [comment]
Could you please provide a minimal sample that reproduces this? I'm not sure how you have Ignite configured in your Spring Boot application.

**Comment by shakuzen** [comment]
@agliznetsov would you be able to provide a minimal sample to reproduce this?

**Comment by izeye** [comment]
`null` guard for the `objectName` has been added in https://github.com/micrometer-metrics/micrometer/commit/bb65f8a195419596229e0c2e6a2cd72c7466dbd6#diff-ad0a51c8efe2154ae8e44660ebcefc3c358a3baaea69042a1ba68b63641300e0R132, so this exception won't happen with the latest releases.

**Comment by shakuzen** [comment]
Closing based on @izeye analysis in https://github.com/micrometer-metrics/micrometer/issues/1797#issuecomment-736977253. We can reopen if there is a remaining issue we can reproduce in a supported version.
