### ISSUE TITLE
gradle fails for local build of v1.0.11

### ISSUE THREAD

**Issue by shelliglick** [micrometer-metrics/micrometer#1802]
Hi, downloaded the zip for v1.0.11, when running ./gradlew pTML it fails with:

`Caused by: java.io.FileNotFoundException: /Users/shelli.g/projects/micrometer-1.0.11/config (Is a directory)
        at org.eclipse.jgit.util.IO.readFully(IO.java:141)
        at org.eclipse.jgit.util.IO.readFully(IO.java:81)
        at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:147)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.loadConfig(BaseRepositoryBuilder.java:719)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.getConfig(BaseRepositoryBuilder.java:696)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.guessWorkTreeOrFail(BaseRepositoryBuilder.java:732)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setupWorkTree(BaseRepositoryBuilder.java:662)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:589)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:612)
        at org.eclipse.jgit.api.Git.open(Git.java:122)
        at org.eclipse.jgit.api.Git.open(Git.java:102)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:85)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
        at org.ajoberstar.grgit.Grgit$__clinit__closure1.doCall(Grgit.groovy:194)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy:65)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        ... 138 more
`

Tried removing the config directory, got this failure:

`Caused by: java.lang.NullPointerException: Cannot set property 'defaultVersionStrategy' on null object
        at io.spring.gradle.release.SpringReleasePlugin$_apply_closure1.doCall(SpringReleasePlugin.groovy:45)
        at io.spring.gradle.release.SpringReleasePlugin.apply(SpringReleasePlugin.groovy:44)
        at io.spring.gradle.release.SpringReleasePlugin.apply(SpringReleasePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
        ... 112 more
`

Please help

**Comment by shakuzen** [comment]
The 1.0.x line is EOL and no longer supported. Why are you trying to build a version from that line instead of using the published artifacts?

**Comment by shakuzen** [comment]
Closing due to lack of response. We can re-open if there's action to take here, but as mentioned, we do not support 1.0.x anymore.
