### ISSUE TITLE
what is the format for specifying elastic.step

### ISSUE THREAD

**Issue by ajay-aggarwal** [micrometer-metrics/micrometer#1820]
All documentation that I came across specify example value as "1m". However when I specify "1m" or "5m" I get following exception. This tells me that it expects string representation for Java Duration class. So should the right value be "PT1m" or "PT5m" ? Please clarify

```
Caused by: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.time.Duration.parse(Duration.java:412) ~[?:1.8.0_212]
	at io.micrometer.core.instrument.push.PushRegistryConfig.step(PushRegistryConfig.java:35) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.step.StepMeterRegistry.newCounter(StepMeterRegistry.java:52) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:522) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:576) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:522) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:245) ~[micrometer-core-1.3.1.jar!/:1.3.1]
	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:128) ~[micrometer-core-1.3.1.jar!/:1.3.1]

```

**Comment by shakuzen** [comment]
How are you configuring your ElasticMeterRegistry?

**Comment by ajay-aggarwal** [comment]
I am using it in a springboot (version 2.2.2.RELEASE) application. And I have a @Bean to return ElasticConfig

```
    @Bean
    public ElasticConfig getElasticConfig() {
        return new ElasticConfig() {
            @Override
            @Nullable
            public String get(String k) {
                ...
            }
        };
    }
```

**Comment by shakuzen** [comment]
Spring Boot offers auto-configuration and configuration properties for most registries, including the `ElasticMeterRegistry` so you don't have to construct it or `ElasticConfig` yourself. See [the Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-export-elastic). To configure the step, you can set the property `management.metrics.export.elastic.step` using Spring Boot's [`Duration` conversion](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-conversion-duration). So you can use `5m` (5 minutes) with Spring Boot's configuration property `management.metrics.export.elastic.step`. If you are making `ElasticConfig` yourself (which there's generally no need to do when using Spring Boot), it will use the default method for the step unless you override it, meaning that you have to use a format that the `Duration#parse` method understands. I'd also note that the default step is 1 minute.
