### ISSUE TITLE
NPEs in DatadogMetricsRegistry.postMetricDescriptionMetadata

### ISSUE THREAD

**Issue by Raibaz** [micrometer-metrics/micrometer#1933]
I'm seeing the following exceptions being thrown:

```
java.lang.NullPointerException: null
at io.micrometer.core.ipc.http.HttpSender$Request$Builder.withContent(HttpSender.java:198) ~[micrometer-core-1.4.0.jar!/:1.4.0]
at io.micrometer.core.ipc.http.HttpSender$Request$Builder.withJsonContent(HttpSender.java:177) ~[micrometer-core-1.4.0.jar!/:1.4.0]
at io.micrometer.datadog.DatadogMeterRegistry.postMetricDescriptionMetadata(DatadogMeterRegistry.java:273) ~[micrometer-registry-datadog-1.4.0.jar!/:1.4.0]
at java.base/java.util.HashMap.forEach(HashMap.java:1336) ~[na:na]
at io.micrometer.datadog.DatadogMeterRegistry.publish(DatadogMeterRegistry.java:150) ~[micrometer-registry-datadog-1.4.0.jar!/:1.4.0]
at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:49) ~[micrometer-core-1.4.0.jar!/:1.4.0]
```

Apparently, this is due to [this](https://github.com/micrometer-metrics/micrometer/pull/1864/files#diff-395bbfe8e8aaa5869c30e470f9d46c71R70) change introduced by #1864 allowing `DatadogMetricMetadata.editDescriptionMetadataBody` to return null, which is not allowed as the content of the PUT request sent by `DatadogMeterRegistry.postMetricDescriptionMetadata`.

There already is a check in place to prevent the request from being sent if metric descriptions are disabled, but there should also be one to check if the content is not null before sending a request.

**Comment by izeye** [comment]
@Raibaz Thanks for the issue!

I created https://github.com/micrometer-metrics/micrometer/pull/1934 to resolve this.
