### ISSUE TITLE
Issue with Micrometer with stackdriver sending to GCP 

### ISSUE THREAD

**Issue by sgrmgj-quotient** [micrometer-metrics/micrometer#1951]
I am creating a sample spring boot microservice which is sending some custom metrics to my GCP 
environment. this is what my config looks like.
```java
@Configuration
public class AppStackdriverConfiguration {
    @Bean
    StackdriverConfig stackdriverConfig() {
        return new StackdriverConfig() {
            @Override
            public String projectId() {
                return "XXXXXX";
            }

            @Override
            public String get(String key) {
                return null;
            }
        };
    }

    @Bean
    StackdriverMeterRegistry meterRegistry(StackdriverConfig stackdriverConfig) {
        return StackdriverMeterRegistry.builder(stackdriverConfig).build();
    }
}
```
and this is how invoke it - 
```java
public class EmployeeEntityListener {
    @Autowired
    private MeterRegistry meterRegistry;

    @PostPersist
    public void updateMetricsAfterCreate(Employee employee) {
        final Counter counter = meterRegistry.counter("employee.joined", "type", "employee");
        counter.increment();
    }

    @PostRemove
    public void updateMetricsAfterDelete(Employee employee) {
        final Counter counter = meterRegistry.counter("employee.resigned", "type", "employee");
        counter.increment();
    }
}
```
But I keep getting error - Is there an issue with stackdriver with micrometer - 

```
[employee-ms-65bc77f856-lssjq server] 2020-03-29 00:15:16.279  WARN 1 --- [trics-publisher] i.m.s.StackdriverMeterRegistry           : failed to send metrics to Stackdriver
[employee-ms-65bc77f856-lssjq server] 
[employee-ms-65bc77f856-lssjq server] com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: An internal error occurred.
[employee-ms-65bc77f856-lssjq server] 	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67) ~[gax-1.48.1.jar:1.48.1]
[employee-ms-65bc77f856-lssjq server] 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-1.48.1.jar:1.48.1]
[employee-ms-65bc77f856-lssjq server] 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-1.48.1.jar:1.48.1]
[employee-ms-65bc77f856-lssjq server] 	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-1.48.1.jar:1.48.1]
[employee-ms-65bc77f856-lssjq server] 	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-1.8.1.jar:na]
[employee-ms-65bc77f856-lssjq server] 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:982) ~[guava-28.0-android.jar:na]
[employee-ms-65bc77f856-lssjq server] 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-28.0-android.jar:na]
[employee-ms-65bc77f856-lssjq server] 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138) ~[guava-28.0-android.jar:na]
[employee-ms-65bc77f856-lssjq server] 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:957) ~[guava-28.0-android.jar:na]
[employee-ms-65bc77f856-lssjq server] 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748) ~[guava-28.0-android.jar:na]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:515) ~[grpc-stub-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490) ~[grpc-stub-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
[employee-ms-65bc77f856-lssjq server] 		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-1.48.1.jar:1.48.1]
[employee-ms-65bc77f856-lssjq server] 		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-1.48.1.jar:1.48.1]
[employee-ms-65bc77f856-lssjq server] 		at com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1156) ~[google-cloud-monitoring-1.93.0.jar:1.93.0]
[employee-ms-65bc77f856-lssjq server] 		at io.micrometer.stackdriver.StackdriverMeterRegistry.publish(StackdriverMeterRegistry.java:176) ~[micrometer-registry-stackdriver-1.3.5.jar:1.3.5]
[employee-ms-65bc77f856-lssjq server] 		at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48) ~[micrometer-core-1.3.5.jar:1.3.5]
[employee-ms-65bc77f856-lssjq server] 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
[employee-ms-65bc77f856-lssjq server] 		... 3 common frames omitted
[employee-ms-65bc77f856-lssjq server] Caused by: io.grpc.StatusRuntimeException: INTERNAL: An internal error occurred.
[employee-ms-65bc77f856-lssjq server] 	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.23.0.jar:1.23.0]
[employee-ms-65bc77f856-lssjq server] 	... 23 common frames omitted
[employee-ms-65bc77f856-lssjq server] 
```
Any help is deeply appreciated.

**Comment by shakuzen** [comment]
The exception doesn't indicate an issue in Micrometer code directly. You're probably better off troubleshooting with Stackdriver help resources to find out more details about the error that occurred. I don't know if there is a way to find more information about these kinds of errors from Stackdriver or not, but that stacktrace would be all the information we have on the Micrometer side.

**Comment by sgrmgj-quotient** [comment]
HI @shakuzen - thanks a ton for your reply - I think I found the solution to my issue. Since your have closed the issue, I am not sure whether I should share the solution here. But yes definitely I agree, that there's nothing wrong with the Micrometer adaptors. Based on your suggestion, I can post the solution which can probably help some others.

**Comment by shakuzen** [comment]
@sgrmgj-quotient yes, please feel free to share the solution here as it may help other Micrometer users that run into it and come across this GitHub issue.
