### ISSUE TITLE
Wavefront apiToken no longer mandatory

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#1964]
If you try to create a `WavefrontRegistry` without an api token this leads to the following

```
Caused by: io.micrometer.core.instrument.config.MissingRequiredConfigurationException: apiToken must be set whenever publishing directly to the Wavefront API
 	at io.micrometer.wavefront.WavefrontMeterRegistry.<init>(WavefrontMeterRegistry.java:106)
 	at io.micrometer.wavefront.WavefrontMeterRegistry.<init>(WavefrontMeterRegistry.java:69)
 	at io.micrometer.wavefront.WavefrontMeterRegistry$Builder.build(WavefrontMeterRegistry.java:448)
 	at org.springframework.boot.actuate.autoconfigure.metrics.export.wavefront.WavefrontMetricsExportAutoConfiguration.wavefrontMeterRegistry(WavefrontMetricsExportAutoConfiguration.java:72)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
 	... 113 more
```

Micrometer recently switched to `WavefrontSender` to publish metrics and such a check is no longer applied. It looks like the creation of the default `WavefrontSender` should fail, [but it does not seem to](https://github.com/micrometer-metrics/micrometer/blob/901651c26f4b8d1991701aa85d66453f2b5fae7f/implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java#L85-L86).

For consistency, it would be nice if Micrometer would throw that exception again.

**Comment by shakuzen** [comment]
I'll add back a similar check we had before to the constructor so we can fail fast.

https://github.com/micrometer-metrics/micrometer/blob/da1e1d09acd7da7779fc7688390381fbc8809959/implementations/micrometer-registry-wavefront/src/main/java/io/micrometer/wavefront/WavefrontMeterRegistry.java#L104-L107

Just to confirm with the Wavefront team, @panghy when sending metrics to a Wavefront proxy, the api token does not need to be configured with the `WavefrontSender`, correct?

**Comment by panghy** [comment]
That is correct

**Comment by snicoll** [comment]
@shakuzen I don't think that fix is correct. As far as I can see, the `apiToken` (and `url` is only used by the `WavefrontSender` now. If you provide a custom `WavefrontSender`, then such a check should not occur anymore (as you may have configured yours with whatever custom settings you need).

I'd rather move those checks in what initializes the default builder and it feels more natural to me to put them there. I am working on a PR now.
