### ISSUE TITLE
Deadlock due to ConcurrentHashMap.compute in PrometheusMeterRegistry

### ISSUE THREAD

**Issue by krm1312** [micrometer-metrics/micrometer#2087]
We just tried to upgrade a relatively large application to spring boot 2.3.0.RC1 which includes micrometer 1.5.0.  The application relies on redis and we have included various metrics for lettuce (redis).

PrometheusMeterRegistry has been modified to use ConcurrentHashMap.compute() at https://github.com/micrometer-metrics/micrometer/blob/93375782923415f1c947f477557ec8b49354f8eb/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L415.

I believe this causing a deadlock for us now in that getting the value of a particular gauge (spring boot health - https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-map-health-indicators-to-metrics) ends up (in different threads) trying to register other timers in the registry which deadlocks.

This doesn't seem like too uncommon of a use-case where getting the value of one meter might trigger initialization of another meter.  It does seem a bit strange to me that registering a meter would trigger getting its value, but, I'm not sure if that changed.

```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks lettuce-kqueueEventLoop-16-1@19158
	 blocks lettuce-kqueueEventLoop-17-1@19751
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	  at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1798)
	  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	  at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1868)
	  at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	  at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:83)
	  at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:118)
	  at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	  at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	  at com.sun.proxy.$Proxy315.info(Unknown Source:-1)
	  at org.springframework.data.redis.connection.lettuce.LettuceServerCommands.info(LettuceServerCommands.java:213)
	  at org.springframework.data.redis.connection.DefaultedRedisConnection.info(DefaultedRedisConnection.java:1345)
	  at org.springframework.boot.actuate.redis.RedisHealthIndicator.doHealthCheck(RedisHealthIndicator.java:64)
	  at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	  at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	  at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:71)
	  at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:39)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:99)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:110)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:96)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:110)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:96)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:74)
	  at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:61)
	  at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:65)
	  at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:55)
	  at com.acme.app.metrics.HealthMetricsConfig.getStatusCode(HealthMetricsConfig.java:38)
	  at com.acme.app.metrics.HealthMetricsConfig$$Lambda$1576.1532832113.applyAsDouble(Unknown Source:-1)
	  at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:47)
	  at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54)
	  at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:210)
	  at io.micrometer.prometheus.PrometheusMeterRegistry$$Lambda$1081.927793961.samples(Unknown Source:-1)
	  at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:69)
	  at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:100)
	  at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
	  at io.prometheus.client.Collector.register(Collector.java:139)
	  at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$17(PrometheusMeterRegistry.java:417)
	  at io.micrometer.prometheus.PrometheusMeterRegistry$$Lambda$1078.840907656.apply(Unknown Source:-1)
	  at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1947)
	  - locked <0x50e3> (a java.util.concurrent.ConcurrentHashMap$Node)
	  at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:413)
	  at io.micrometer.prometheus.PrometheusMeterRegistry.newGauge(PrometheusMeterRegistry.java:207)
	  at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:295)
	  at io.micrometer.core.instrument.MeterRegistry$$Lambda$1062.593058251.apply(Unknown Source:-1)
	  at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:559)
	  at io.micrometer.core.instrument.MeterRegistry$$Lambda$1064.592248212.apply(Unknown Source:-1)
	  at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:612)
	  - locked <0x50e4> (a java.lang.Object)
	  at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:566)
	  at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:559)
	  at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:295)
	  at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:190)
	  at io.micrometer.core.instrument.composite.CompositeGauge.registerNewMeter(CompositeGauge.java:58)
	  at io.micrometer.core.instrument.composite.CompositeGauge.registerNewMeter(CompositeGauge.java:27)
	  at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
	  at io.micrometer.core.instrument.composite.CompositeMeterRegistry$$Lambda$1067.482729490.accept(Unknown Source:-1)
	  at java.lang.Iterable.forEach(Iterable.java:75)
	  at java.util.Collections$SetFromMap.forEach(Collections.java:5581)
	  at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
	  at io.micrometer.core.instrument.composite.CompositeMeterRegistry$$Lambda$1066.1535995916.run(Unknown Source:-1)
	  at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
	  at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
	  at io.micrometer.core.instrument.composite.CompositeMeterRegistry$$Lambda$1031.891077813.accept(Unknown Source:-1)
	  at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:622)
	  - locked <0x50e5> (a java.lang.Object)
	  at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:566)
	  at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:559)
	  at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:295)
	  at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:190)
	  at com.acme.app.metrics.HealthMetricsConfig.init(HealthMetricsConfig.java:34)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
	  at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	  at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	  - locked <0x50e6> (a java.lang.Object)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	  at com.acme.AcmeUserWeb.main(AcmeUserWeb.java:48)`

lettuce-kqueueEventLoop-16-1@19158" daemon prio=5 tid=0x200 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for main@1 to release lock on <0x50e5> (a java.lang.Object)
	  at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:596)
	  at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:566)
	  at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:306)
	  at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:538)
	  at com.acme.redis.appmetrics.LettuceMetrics.lambda$recordCommandLatency$2(LettuceMetrics.java:61)
	  at com.acme.redis.appmetrics.LettuceMetrics$$Lambda$1433.570540964.apply(Unknown Source:-1)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2380)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$1434.2007041160.apply(Unknown Source:-1)
	  at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	  - locked <0x50ec> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2378)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2361)
	  at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	  at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	  at com.acme.redis.appmetrics.LettuceMetrics.recordCommandLatency(LettuceMetrics.java:57)
	  at io.lettuce.core.protocol.CommandHandler.recordLatency(CommandHandler.java:787)
	  at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:670)
	  at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:596)
	  at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	  at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
	  at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:376)
	  at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:211)
	  at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:834)
```

```java
public class LettuceMetrics implements CommandLatencyCollector {

    private String redisName;
    private MeterRegistry meterRegistry;

    /**
     * Keyed by protocol keyword name.
     */
    private Cache<String, Timer> firstResponseTimers = Caffeine.newBuilder().expireAfterAccess(1, TimeUnit.DAYS)
        .removalListener((String key, Timer timer, RemovalCause cause) -> {
            if (null != timer) {
                meterRegistry.remove(timer);
            }
        }).build();

    private Cache<String, Timer> completionResponseTimers = Caffeine.newBuilder().expireAfterAccess(1, TimeUnit.DAYS)
        .removalListener((String key, Timer timer, RemovalCause cause) -> {
            if (null != timer) {
                meterRegistry.remove(timer);
            }
        }).build();

    public LettuceMetrics(MeterRegistry meterRegistry, String redisName) {
        this.redisName = redisName;
        this.meterRegistry = meterRegistry;
    }

    public LettuceMetrics(MeterRegistry meterRegistry) {
        this.redisName = "unnamed";
        this.meterRegistry = meterRegistry;
    }

    @Override
    public void recordCommandLatency(SocketAddress local, SocketAddress remote, ProtocolKeyword protocolKeyword,
                                     long firstResponseLatency, long completionLatency) {

        if (null != meterRegistry) {
            firstResponseTimers.get(protocolKeyword.name(), (key) ->
                Timer.builder("lettuce.first.response.latency")
                    .description("Latency between command send and first response (first response received)")
                    .tags("command", key, "redisName", redisName)
                    .register(meterRegistry))
                .record(firstResponseLatency, TimeUnit.NANOSECONDS);

            completionResponseTimers.get(protocolKeyword.name(), (key) ->
                Timer.builder("lettuce.completion.latency")
                    .description("Latency between command send and command completion (complete response received)")
                    .tags("command", key, "redisName", redisName)
                    .register(meterRegistry))
                .record(completionLatency, TimeUnit.NANOSECONDS);
        }

    }

    @Override
    public void shutdown() {
        // noop
    }

    @Override
    public Map<CommandLatencyId, CommandMetrics> retrieveMetrics() {
        return Collections.emptyMap();
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
```

**Comment by izeye** [comment]
@krm1312 Thanks for the report!

If I understand correctly, I can't see any deadlock in the stack trace, but I can only see blocking due to metric value collection that didn't happen before. The reason why the metric value collection happens is due to the support for Prometheus `CollectorRegistry`'s auto-describe made in https://github.com/micrometer-metrics/micrometer/pull/1885.

Spring Boot enables it by default, so you can disable it by defining your own `CollectorRegistry` as follows:

```java
	@Bean
	public CollectorRegistry collectorRegistry() {
		return new CollectorRegistry(false);
	}
```

I'm not sure if enabling auto-describe is a good default value based on the current behavior, and I'm not sure how the current behavior could be improved with auto-describe enabled, either.

**Comment by krm1312** [comment]
Eventually the lettuce command will timeout and fail, so, not a deadlock that can be detected by the JVM.  But, you can see lettuce-kqueueEventLoop-16-1@19158 is waiting on main to release 0x50e5 (which is the concurrent hash map).  But, main is waiting for lettuce-kqueueEventLoop-16-1@19158 to complete the lettuce (redis) command before proceeding.

**Comment by izeye** [comment]
@krm1312 Sorry, I misread the stack trace. You're right.

**Comment by izeye** [comment]
Unfortunately, I couldn't find an easy way to fix this with the auto-describe support at the moment.

I created https://github.com/micrometer-metrics/micrometer/pull/2090 to revert it in case we couldn't find a solution before the next release.

**Comment by izeye** [comment]
I created #2103 for alternative solution for #1883.

**Comment by krm1312** [comment]
Was hoping this would make it into boot 2.3.1.  Any chance 1.5.2 will be released in time to make it into boot 2.3.2 managed deps?

**Comment by jkschneider** [comment]
@izeye I don't know about this case, but this is why I started to distrust CHM. We previously used pcollections which can't be deadlocked and have similar performance characteristics. But then dependency hygiene... Not sure what is the best outcome.

**Comment by shakuzen** [comment]
@krm1312 looks like Spring Boot 2.3.1 has already been released. We'll work on getting Micrometer 1.5.2 out soon. You can always override the managed version of Micrometer when that's released. You don't need to wait until a Spring Boot release has upgraded to it.
