### ISSUE TITLE
ArrayIndexOutOfBoundsException in TimeWindowLatencyHistogram

### ISSUE THREAD

**Issue by shabino** [micrometer-metrics/micrometer#230]
Found in my logs.  Running 1.0.0.RC3 w/ Spring Boot 2.0.0.M6.  Please let me know if there's any other data I can provide.

Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
        at io.micrometer.core.instrument.histogram.TimeWindowLatencyHistogram.rotate(TimeWindowLatencyHistogram.java:77)
        at io.micrometer.core.instrument.histogram.TimeWindowLatencyHistogram.record(TimeWindowLatencyHistogram.java:62)
        at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:88)
        at io.micrometer.core.instrument.composite.CompositeTimer.lambda$record$0(CompositeTimer.java:43)
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:43)
        at org.springframework.boot.actuate.metrics.web.client.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:75)
        at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:92)
        at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:76)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:714)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:681)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:626)

**Comment by jkschneider** [comment]
Thanks, we've done a bit of overhauling of the rotate mechanism for rc4, but I'll check to see whether this is still possible.

**Comment by jkschneider** [comment]
Appears this was due to a lack of synchronization in `rotate`.

**Comment by jkschneider** [comment]
Fixed in ccc3811.
