### ISSUE TITLE
Deadlock on TelegrafStatsdLineBuilder

### ISSUE THREAD

**Issue by veera-chenna** [micrometer-metrics/micrometer#2325]
Hi,

We have recently upgraded to 1.5.4 version of Micrometer from 1.3.x and after that we have encountered deadlocks and blocked threads  while using the Telegraf Statsd registry. I can see a similar issue which was fixed in the `DatadogStatsdLineBuilder` class for the issue reported [here](https://github.com/micrometer-metrics/micrometer/issues/2100).  Following is the deadlock info,

```
"http-nio-8080-exec-42":
  waiting to lock monitor 0x00007f56f02ded28 (object 0x00000006c74e71b8, a java.util.concurrent.ConcurrentHashMap$ReservationNode),
  which is held by "http-nio-8080-exec-4"
"http-nio-8080-exec-4":
  waiting to lock monitor 0x00007f56d02015d8 (object 0x00000006c74c39c0, a java.lang.Object),
  which is held by "http-nio-8080-exec-3"
"http-nio-8080-exec-3":
  waiting to lock monitor 0x00007f56f02ded28 (object 0x00000006c74e71b8, a java.util.concurrent.ConcurrentHashMap$ReservationNode),
  which is held by "http-nio-8080-exec-4"
```

Thread-1:
```
"http-nio-8080-exec-42":
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1674)
        - waiting to lock <0x00000006c74e71b8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.tagsByStatistic(TelegrafStatsdLineBuilder.java:71)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.line(TelegrafStatsdLineBuilder.java:47)
        at io.micrometer.statsd.internal.FlavorStatsdLineBuilder.count(FlavorStatsdLineBuilder.java:46)
        at io.micrometer.statsd.StatsdLineBuilder.count(StatsdLineBuilder.java:30)
        at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:44)
        at io.micrometer.core.instrument.composite.CompositeCounter.lambda$increment$0(CompositeCounter.java:31)
        at io.micrometer.core.instrument.composite.CompositeCounter$$Lambda$124/1311144776.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:47)
        at io.micrometer.core.instrument.composite.CompositeCounter.increment(CompositeCounter.java:31)
        at io.micrometer.core.instrument.Counter.increment(Counter.java:37)
        at com.mmint.common.perf.micrometer.MicrometerStatsHelper.incrementCounter(MicrometerStatsHelper.java:77)
        at com.mmint.common.perf.MetricsCollector.incrementCounter(MetricsCollector.java:38)
```

Thread-2:
```
"http-nio-8080-exec-4":
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.telegrafTag(TelegrafStatsdLineBuilder.java:75)
        - waiting to lock <0x00000006c74c39c0> (a java.lang.Object)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder$$Lambda$337/1980680110.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        - locked <0x00000006c74e71b8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.tagsByStatistic(TelegrafStatsdLineBuilder.java:71)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.line(TelegrafStatsdLineBuilder.java:47)
        at io.micrometer.statsd.internal.FlavorStatsdLineBuilder.count(FlavorStatsdLineBuilder.java:46)
        at io.micrometer.statsd.StatsdLineBuilder.count(StatsdLineBuilder.java:30)
        at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:44)
        at io.micrometer.core.instrument.composite.CompositeCounter.lambda$increment$0(CompositeCounter.java:31)
        at io.micrometer.core.instrument.composite.CompositeCounter$$Lambda$124/1311144776.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:47)
        at io.micrometer.core.instrument.composite.CompositeCounter.increment(CompositeCounter.java:31)
        at io.micrometer.core.instrument.Counter.increment(Counter.java:37)
        at com.mmint.common.perf.micrometer.MicrometerStatsHelper.incrementCounter(MicrometerStatsHelper.java:77)
        at com.mmint.common.perf.MetricsCollector.incrementCounter(MetricsCollector.java:38)
```

Thread-3:
```
"http-nio-8080-exec-3":
        at java.util.concurrent.ConcurrentHashMap.clear(ConcurrentHashMap.java:1193)
        - waiting to lock <0x00000006c74e71b8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.updateIfNamingConventionChanged(TelegrafStatsdLineBuilder.java:57)
        - locked <0x00000006c74c39c0> (a java.lang.Object)
        at io.micrometer.statsd.internal.TelegrafStatsdLineBuilder.line(TelegrafStatsdLineBuilder.java:46)
        at io.micrometer.statsd.internal.FlavorStatsdLineBuilder.count(FlavorStatsdLineBuilder.java:46)
        at io.micrometer.statsd.StatsdLineBuilder.count(StatsdLineBuilder.java:30)
        at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:44)
        at io.micrometer.core.instrument.composite.CompositeCounter.lambda$increment$0(CompositeCounter.java:31)
        at io.micrometer.core.instrument.composite.CompositeCounter$$Lambda$124/1311144776.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:47)
        at io.micrometer.core.instrument.composite.CompositeCounter.increment(CompositeCounter.java:31)
        at io.micrometer.core.instrument.Counter.increment(Counter.java:37)
        at com.mmint.common.perf.micrometer.MicrometerStatsHelper.incrementCounter(MicrometerStatsHelper.java:77)
        at com.mmint.common.perf.MetricsCollector.incrementCounter(MetricsCollector.java:38)
```

Thank you

**Comment by izeye** [comment]
@veera-chenna Thanks for the issue. I created #2326 to try to resolve this.
