### ISSUE TITLE
NullPointerException in JvmMemory.isOldGenPool in 1.6.0 with unknown gc pool name

### ISSUE THREAD

**Issue by ebullient** [micrometer-metrics/micrometer#2330]
```
Caused by: java.lang.NullPointerException
        at io.micrometer.core.instrument.binder.jvm.JvmMemory.isOldGenPool(JvmMemory.java:50)
        at io.micrometer.core.instrument.binder.jvm.JvmHeapPressureMetrics.bindTo(JvmHeapPressureMetrics.java:81)
        at io.quarkus.micrometer.runtime.MicrometerRecorder.configureRegistries(MicrometerRecorder.java:100)
        at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry-2125003310.deploy_0(MicrometerProcessor$configureRegistry-2125003310.zig:144)
        at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry-2125003310.deploy(MicrometerProcessor$configureRegistry-2125003310.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:477)
```

**Comment by izeye** [comment]
@ebullient Thanks for the issue. I created #2333 to try to resolve this.

**Comment by ebullient** [comment]
I was in the middle of making a PR for you. ;) let me pull yours.
