### ISSUE TITLE
[Question] Does HibernateMetrics support Hibernate4.x?

### ISSUE THREAD

**Issue by vchau** [micrometer-metrics/micrometer#2368]
Hi,

I have a Spring MVC application using Hibernate 4.3.11.Final.  Is this supported?

I am just trying out `HibernateMetrics` from version 1.6.1 and unfortunately, am getting the following exception on initialization

```
java.lang.NoSuchMethodError: org.hibernate.stat.Statistics.getDomainDataRegionStatistics(Ljava/lang/String;)Lorg/hibernate/stat/CacheRegionStatistics;
	at io.micrometer.core.instrument.binder.jpa.HibernateMetrics.hasDomainDataRegionStatistics(HibernateMetrics.java:256)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.micrometer.core.instrument.binder.jpa.HibernateMetrics.bindTo(HibernateMetrics.java:184)
```

i am simply registering the Hibernate session factory like so:

```
        Map<String, EntityManagerFactory> allEmf = appContext.getBeansOfType(EntityManagerFactory.class);
        for (Map.Entry<String,EntityManagerFactory> emf : allEmf.entrySet()) {
            SessionFactory sessionFactory = 
            		emf.getValue().unwrap(SessionFactory.class);
            new HibernateMetrics(sessionFactory, emf.getKey(), Collections.emptyList()).bindTo(registry);        	
        }
```

**Comment by shakuzen** [comment]
As mentioned in the [1.6 release notes](https://github.com/micrometer-metrics/micrometer/releases/tag/v1.6.0):

> `HibernateMetrics` requires Hibernate 5.3 or later now.

So the 1.6.x line will definitely not work with Hibernate 4.3. The 1.5.x release line may have better luck working with Hibernate 4.3, though we don't test against it and therefore do not intentionally support it. Feel free to share your results here for others' benefit if you try that.
