### ISSUE TITLE
Support override gauge name in DatabaseTableMetrics constructor

### ISSUE THREAD

**Issue by mkuzhaleu** [micrometer-metrics/micrometer#2390]
Add ability to override the default name of the gauge "db.table.size" in the `io.micrometer.core.instrument.binder.db.DatabaseTableMetrics`

It could be done as an additional constructor:

```
    public DatabaseTableMetrics(String gaugeName, DataSource dataSource, String query, String dataSourceName, String tableName, Iterable<Tag> tags) { ... }
```

This is a nice to have feature as sometimes we can specify different tags for different DatabaseTableMetrics and this could cause the issue for PrometheusMeterRegistty:

```
Caused by: java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'db_table_size_rows' containing tag keys [db, tagA, tagB, table]. The meter you are attempting to register has keys [db, table].
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:420)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:404)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newGauge(PrometheusMeterRegistry.java:206)
```

**Comment by jonatan-ivanov** [comment]
fyi: you can rename any meter using a `MeterFilter`.
