### ISSUE TITLE
Micrometer with Prometheus MeterRegistry.getMappedId NPE during autoconfiguration of prometheusMeterRegistry

### ISSUE THREAD

**Issue by tonydvp** [micrometer-metrics/micrometer#2450]
Hello, I have the following dependencies:

 ```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.4.2</version>
    
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>
  </parent>
```

Here is my configuration to add custom commonTags (even though it doesn't work with or without it):

```
@Component
@ConditionalOnProperty(value = "micrometer.tracing", havingValue = "true")
public class MicrometerServiceRegistryConfig {

  @Value("${spring.application.name}")
  String appName;

  @Value("${spring.application.name}.${hostLocation}")
  String environment;

  @Value("${spring.application.name}.${originSystemId}")
  String originSystemId;

  @Bean
  MeterRegistryCustomizer<PrometheusMeterRegistry> metricsCommonTags() {
    return registry ->
        registry
            .config()
            .commonTags("appName", appName, "env", environment, "originSystemId", originSystemId);
  }
}
```

Here is the exception I get while running the app:
```
Caused by: java.lang.NullPointerException: null
	at io.micrometer.core.instrument.MeterRegistry.getMappedId(MeterRegistry.java:581) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:567) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:561) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:297) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:190) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics.bindTo(JvmGcMetrics.java:109) ~[micrometer-core-1.6.3.jar:1.6.3]
	at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics$$FastClassBySpringCGLIB$$ee2e3c7e.invoke(<generated>) ~[micrometer-core-1.6.3.jar:1.6.3]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:180) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:180) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.3.jar:5.3.3]
	at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics$$EnhancerBySpringCGLIB$$5a0af4c.bindTo(<generated>) ~[micrometer-core-1.6.3.jar:1.6.3]
	at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryConfigurer.lambda$addBinders$1(MeterRegistryConfigurer.java:86) ~[spring-boot-actuator-autoconfigure-2.4.2.jar:2.4.2]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[na:na]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[na:na]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryConfigurer.addBinders(MeterRegistryConfigurer.java:86) ~[spring-boot-actuator-autoconfigure-2.4.2.jar:2.4.2]
	at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryConfigurer.configure(MeterRegistryConfigurer.java:68) ~[spring-boot-actuator-autoconfigure-2.4.2.jar:2.4.2]
	at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryPostProcessor.postProcessAfterInitialization(MeterRegistryPostProcessor.java:64) ~[spring-boot-actuator-autoconfigure-2.4.2.jar:2.4.2]
	at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryPostProcessor$$FastClassBySpringCGLIB$$eaee8bc2.invoke(<generated>) ~[spring-boot-actuator-autoconfigure-2.4.2.jar:2.4.2]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:180) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:180) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryPostProcessor$$EnhancerBySpringCGLIB$$285b4798.postProcessAfterInitialization(<generated>) ~[spring-boot-actuator-autoconfigure-2.4.2.jar:2.4.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:444) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[spring-beans-5.3.3.jar:5.3.3]
	... 80 common frames omitted
```
	
I am using the latest Spring version (2.4.2)	

I found out while debugging that the PrometheusMeterRegistry was instantiated just fine:
![Screenshot 2021-02-15 at 14 24 08](https://user-images.githubusercontent.com/15218429/107946785-2d43d900-6f9a-11eb-8dbc-914d3bbbff0a.png)

But later on, when the **JvmMetricsAutoConfiguration** tried to configure a **JvmGcMetrics**, the **public void bindTo(MeterRegistry registry)** got invoked with a PrometheusMeterRegistry which was EnhancerBySpring instance:

![Screenshot 2021-02-15 at 14 24 37](https://user-images.githubusercontent.com/15218429/107947090-93c8f700-6f9a-11eb-9078-46dac1150272.png)

Which had null values for all of it's properties. This led to the NPE.

**Comment by izeye** [comment]
@tonydvp Thanks for the issue.

I tried to reproduce this with [a sample project](https://github.com/izeye/sample-micrometer-spring-boot/tree/micrometer-gh-2450) based on the code snippets you shared, but I couldn't. Could you provide a sample project to reproduce it?

**Comment by tonydvp** [comment]
Hello, it seemed that I thought I had spring-boot-starter-actuator dependancy coming from another dependancy. I tried to explicitly add it to my project and now it is all fine. @izeye thanks for looking into this in such a short notice. Ideally it would have been better to have something indicating this better than an NPE, but i suppose it is a sneaky case.

**Comment by izeye** [comment]
@tonydvp Thanks for letting us know. I don't fully understand your setup, but glad to hear that you figured it out.
