### ISSUE TITLE
ClassCastException in CompositeMeterRegistry.add()

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#255]
Seems like some meters in `CompositeMeterRegistry` is not a `CompositeMeter`? Any clues? The exception does not always occur, though.

```
java.lang.ClassCastException: io.micrometer.core.instrument.MeterRegistry$More$1 cannot be cast to io.micrometer.core.instrument.composite.CompositeMeter
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$add$0(CompositeMeterRegistry.java:111)
	at java.util.HashMap$Values.forEach(HashMap.java:980)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at io.micrometer.core.instrument.MeterRegistry.forEachMeter(MeterRegistry.java:185)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.add(CompositeMeterRegistry.java:111)
	at io.micrometer.core.instrument.Metrics.addRegistry(Metrics.java:33)
	at io.micrometer.spring.autoconfigure.MetricsAutoConfiguration$MeterRegistryConfigurationSupport.<init>(MetricsAutoConfiguration.java:138)
	at io.micrometer.spring.autoconfigure.MetricsAutoConfiguration$MeterRegistryConfigurationSupport$$EnhancerBySpringCGLIB$$be7c6da1.<init>(<generated>)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 67 common frames omitted
```

**Comment by checketts** [comment]
I finally got around to upgrading from rc2 to rc5 and hit this error. Could we release an rc6 to get past this bug?
