### ISSUE TITLE
Questions/Problems regarding commons-dbcp2 metrics

### ISSUE THREAD

**Issue by jjank** [micrometer-metrics/micrometer#2593]
Hi everybody,

first of all thanks for working on micrometer - it is a true lifesaver 😃 

I'm having trouble getting metrics out of apache commons dbcp2 data sources. I've set up a [minimal working example](https://github.com/wengertj/micrometer-dbcp2) to illustrate my problems.

## Problem description

Disclaimer - I am terribly unfamiliar with JMX so it is very much possible, that this is the root cause of the problem.

I've configured the `org.apache.commons.dbcp2.BasicDataSource` with the following JMX-name: `org.apache.commons.pool2:name=dbcp,type=GenericObjectPool`. 

After a little bit of digging through the source code of `BasicDataSource` this is necessary as JXM will not be enabled otherwise (this seems strange to me because the "vanilla" `GenericObjectPool` has a different behaviour).

If my understanding of `CommonsObjectPool2Metrics` is correct this name pattern is necessary in order for Micrometer to register this pool ? 

When running the application (or the test in my example repo) I encounter the following erros in the log:

```
SEVERE: can not set name tag
javax.management.AttributeNotFoundException: No such attribute: FactoryType
	at java.management/com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:81)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:641)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.nameTag(CommonsObjectPool2Metrics.java:141)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.lambda$registerNotificationListener$1(CommonsObjectPool2Metrics.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

May 07, 2021 1:25:15 PM io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics lambda$registerNotificationListener$1
SEVERE: can not set name tag
javax.management.InstanceNotFoundException: org.apache.commons.pool2:name=dbcp,type=GenericObjectPool,connectionpool=connections,connection=0
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1083)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:637)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.nameTag(CommonsObjectPool2Metrics.java:141)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.lambda$registerNotificationListener$1(CommonsObjectPool2Metrics.java:193)
``` 

It seems that:
* The `FactoryType` is not set by dbcp2
* dbcp registeres every connection with jmx but the connection does not seem to have a `name` property

So my questions are:
* Have I misconfigured the JMX-Name?
* More generaly: Would it be valuable to implement a dedicated `MeterBinder` for commons dbcp2 that will handle the (JMX)-specific more explicitly? Or should `CommonsObjectPool2Metrics` be more graceful/resillient/configurable?

Thanks a lot in advance 👍

**Comment by shakuzen** [comment]
We still have #1710 open for specifically supporting metrics of Apache DBCP2. It was suggested in #1712 that the `CommonsObjectPool2Metrics` could be used to get some metrics from DBCP2, but I don't know if anyone actually tested that. We could be more defensive about the FactoryType not being present, though.

**Comment by wengertj** [comment]
With the configuration I described you _actually_ get metrics from DBCP2 - I should have been more clear about that. You "just" will see a lot of errors in the log 😬 

`CommonsObjectPool2Metrics` seems to be a good basis for supporting DBCP2. I think there are a couple of valid approaches for fully supporting DBCP2. One of them might be to extract the JMX-querying code and let  `CommonsObjectPool2Metrics` and some `DBCP2Metrics` delegate to that. 

Maybe the DBCP2 devs will be able to provide some guidance too?

**Comment by fzyzcjy** [comment]
Hi, I am seeing this bug in my code today with latest versions. Is there any updates? Thanks!

**Comment by jonatan-ivanov** [comment]
Latest Micrometer and latest DBCP2?
Could you please check that the object that the log entry is complaining about is available through JMX (jconsole, JMC, visualvm, etc.)?

**Comment by fzyzcjy** [comment]
@jonatan-ivanov Hi thanks for the reply! I will check that

**Comment by jjank** [comment]
Hi there !

I noticed that as of version `2.10.0` the underlying Connection pool (i.e. the `org.apache.commons.pool2.impl.GenericObjectPool`) is exposed publicly: https://github.com/apache/commons-dbcp/commit/54ef9d3d7ee4d07d792d287c768f8b402306e55b in [BasicDataSource.java](https://github.com/apache/commons-dbcp/blob/master/src/main/java/org/apache/commons/dbcp2/BasicDataSource.java#L770). (In a [previous discussion](https://github.com/micrometer-metrics/micrometer/pull/1712#discussion_r349060838) this was the main motivation for using JMX in `CommonsObjectPool2Metrics`)

This seems to be a deliberate choice - though I could not find an explanation/motivation in the [respective mailing lists](https://svn-master.apache.org/repos/infra/websites/production/commons/content/proper/commons-dbcp/mailing-lists.html)

This would make it quite easy to instrument because `GenericObjectPool` provides methods for all common metrics.

There's a couple of ways how to go forward:

1. "Just" implement a `MeterBinder` for `BasicDataSource` and ignore [CommonsObjectPool2Metrics](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/commonspool2/CommonsObjectPool2Metrics.java). To me this does not seem a great choice because:
    - it would require a dependency (albeit optional) on `commons-dpcp2` in micrometer
    - a lot of duplication of code that exists in `CommonsObjectPool2Metrics` which leads to
2. Enhance `CommonsObjectPool2Metrics` to also gather metrics directly from a (user-passed) reference of `GenericObjectPool` in addition to querying jmx

I'd be willing to contribute since instrumenting dbcp would greatly benefit the app I'm currently maintaining (I have 0 experience with the Observation api though). But I'm not sure If you - in the long term - would rather like to see libraries provide instrumentation themselves and thus reduce the maintainance burden on micrometer. On the other hand recent PRs auch as https://github.com/micrometer-metrics/micrometer/pull/4037 have put in a lot of effort in improving 3rd-party libs instrumentation 🤔  

Thoughts @jonatan-ivanov ?

**Comment by raymondchen625** [comment]
I ran into the same "missing the FactoryType attribute" issue when I was using `CommonsObjectPool2Metrics` to collect metrics.
The `GenericObjectPool` and `GenericObjectPoolMXBean` indeed have the `FactoryType` property. That might be the reason why `CommonsObjectPool2Metrics` expects it. But the `BasicDataSource` doesn't implement/extend `GenericObjectPool`, hence no `FactoryType` property. It only [uses GenericObjectPool internally](https://github.com/apache/commons-dbcp/blob/d73cae3b70f5d9c6df5bd8e76b4cc07e82b2248d/src/main/java/org/apache/commons/dbcp2/BasicDataSource.java#L357-L360).
It appears to me the purpose of [getting the FactoryType](https://github.com/micrometer-metrics/micrometer/blob/9b4413e25b992a381feb96aaf927b42b0256ee76/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/commonspool2/CommonsObjectPool2Metrics.java#L135-L144) is just to add it to the tags. Not sure why we want to mandate this. If we stop getting the `FactoryType` attribute and adding it to the tags, the problem will be solved.

**Comment by jjank** [comment]
> It appears to me the purpose of [getting the FactoryType](https://github.com/micrometer-metrics/micrometer/blob/9b4413e25b992a381feb96aaf927b42b0256ee76/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/commonspool2/CommonsObjectPool2Metrics.java#L135-L144) is just to add it to the tags. Not sure why we want to mandate this.

I can think of one reason: If you happen to have more than one object pool in your application for different purposes (some libraries use the pool under the hood) it is hard if not impossible to distinguish between different pools in the metrics.

**Comment by raymondchen625** [comment]
> it is hard if not impossible to distinguish between different pools in the metrics

The `name` tag can be used to distinguish different pools. Actually, the non-configurable `name` tag might also causes naming conflict issue.

**Comment by shakuzen** [comment]
https://github.com/micrometer-metrics/micrometer/pull/5316 was merged, which should address the FactoryType issue. What's the remaining issue for getting metrics on BasicDataSource? I understand now things go through JMX and that needs to be configured on the BasicDataSource. Are things not working when doing that with the latest versions of Micrometer? I agree an option to directly bind metrics for a `GenericObjectPool` instance might be nice rather than having to go through JMX, but I'm trying to understand if the instrumentation via JMX works for BasicDataSource now or not.

**Comment by jjank** [comment]
I've updated my [example repo](https://github.com/jjank/micrometer-dbcp2) to use the latest versions of both micrometer and commons-dbcp2.

I've set a jmx name on BasicDataSource ([link](https://github.com/jjank/micrometer-dbcp2/blob/main/src/test/java/com/github/wengertj/AppTest.java#L50))
```java
ds.setJmxName("org.apache.commons.pool2:type=GenericObjectPool");
```

Using JDK Mission control and the mbean browser I can see that the datasouce registered something in JMX:

<img width="1089" alt="Image" src="https://github.com/user-attachments/assets/ac9bfc92-b771-479b-a915-a6d219db66f9" />

However - [as can be seen in the logs](https://github.com/jjank/micrometer-dbcp2/actions/runs/12910157552/job/35999593104#step:4:39) there's still strange issues when micrometer tries to read the `factoryType`

<details>
<summary><b>Logs</b></summary>


```
Jan 22, 2025 3:43:00 PM io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics lambda$registerNotificationListener$1
SEVERE: can not set name tag
javax.management.AttributeNotFoundException: No such attribute: FactoryType
	at java.management/com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:81)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
	at java.management/javax.management.StandardMBean.getAttribute(StandardMBean.java:372)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:636)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:679)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.getFactoryType(CommonsObjectPool2Metrics.java:139)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.nameTag(CommonsObjectPool2Metrics.java:132)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.lambda$registerNotificationListener$1(CommonsObjectPool2Metrics.java:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

Jan 22, 2025 3:43:04 PM io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics lambda$registerNotificationListener$1
SEVERE: can not set name tag
javax.management.InstanceNotFoundException: org.apache.commons.pool2:type=GenericObjectPool,connectionpool=connections,connection=0
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1073)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:632)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:679)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.getFactoryType(CommonsObjectPool2Metrics.java:139)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.nameTag(CommonsObjectPool2Metrics.java:132)
	at io.micrometer.core.instrument.binder.commonspool2.CommonsObjectPool2Metrics.lambda$registerNotificationListener$1(CommonsObjectPool2Metrics.java:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```
</details>

As per the JMX screenshot a factory type does exist. But as I said eary on I have little to no understanding of JMX, specifically  how to [MBeanServer query](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/commonspool2/CommonsObjectPool2Metrics.java#L148) works exactly is not really clear to me.

My best guesses are:
* I've set the wrong JMX name (quite likely)
* The "structure" of the MBeans is different from "plain old" GenericObjectPool - therefore the queries in `CommonsObjectPool2Metrics` don't work as expected

From my perspective this issue could be closed, since it is quite easy to instrument `BasicDataSource` now that the pool is exposed directly. Your call @shakuzen
