### ISSUE TITLE
StatsdMeterRegistry OverflowException: Can't deliver value due to lack of requests

### ISSUE THREAD

**Issue by qiujiayu** [micrometer-metrics/micrometer#2595]
on spring boot 2.3 use io.micrometer:micrometer-registry-statsd:1.6.5

```
io.micrometer.shaded.reactor.core.Exceptions$OverflowException: Can't deliver value due to lack of requests
	at io.micrometer.shaded.reactor.core.Exceptions.failWithOverflow(Exceptions.java:234)
	at io.micrometer.shaded.reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:346)
	at io.micrometer.shaded.reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:148)
	at io.micrometer.shaded.reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
	at io.micrometer.shaded.reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.lambda$next$1(LogbackMetricsSuppressingFluxSink.java:49)
	at io.micrometer.core.instrument.binder.logging.LogbackMetrics.ignoreMetrics(LogbackMetrics.java:114)
	at io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.next(LogbackMetricsSuppressingFluxSink.java:49)
	at io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.next(LogbackMetricsSuppressingFluxSink.java:25)
	at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:44)
	at io.micrometer.core.instrument.Counter.increment(Counter.java:37)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:195)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.info(Logger.java:595)
```

**Comment by checketts** [comment]
Can you please add more detail? Does this happen immediately or after a period of time? Can you reproduce it with a simple project?  Are you able to upgrade to the latest spring boot/micrometer and still see this behavior?

**Comment by shakuzen** [comment]
In addition to @checketts questions, is the exception happening intermittently? Does it recover and properly send metrics after this?

**Comment by shakuzen** [comment]
Thank you for the response. We will need more details on how to reproduce this so we can fix it. Does it still happen on the latest versions?

**Comment by shakuzen** [comment]
Are you calling `stop` on `StatsdMeterRegistry`? After chatting with @simonbasle, it sounds like a subscriber isn't requesting elements. How is your `StatsdMeterRegistry` configured? Are you using UDP, TCP, or a custom `lineSink`?

**Comment by qiujiayu** [comment]
`StatsdMeterRegistry` configured by `org.springframework.boot.actuate.autoconfigure.metrics.export.statsd.StatsdMetricsExportAutoConfiguration` and Properties :

```
management.metrics.export.statsd.enabled: true # Whether exporting of metrics to StatsD is enabled.
management.metrics.export.statsd.flavor: datadog # StatsD line protocol to use.
management.metrics.export.statsd.host: ${log.datadog.statsd.host} # Host of the StatsD server to receive exported metrics.
management.metrics.export.statsd.max-packet-length: 1400 # Total length of a single payload should be kept within your network's MTU.
management.metrics.export.statsd.polling-frequency: 1s # How often gauges will be polled. When a gauge is polled, its value is recalculated and if the value has changed (or publishUnchangedMeters is true), it is sent to the StatsD server.
management.metrics.export.statsd.port: ${log.datadog.statsd.port} # Port of the StatsD server to receive exported metrics.
management.metrics.export.statsd.publish-unchanged-meters: true # Whether to send unchanged meters to the StatsD server.
```

**Comment by shakuzen** [comment]
How often does this happen?
Can you reproduce it in a sample project we can run?

**Comment by shakuzen** [comment]
@qiujiayu are you able to reproduce this issue in a project we can run?

**Comment by shakuzen** [comment]
Closing due to lack of feedback. If we can reproduce this, we will reopen and investigate further.
