### ISSUE TITLE
LongTaskTimer: Failed to register Collector of type MicrometerCollector: The Collector exposes the same name multiple times

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2765]
[Newly released 0.12.0](https://github.com/prometheus/client_java/releases/tag/parent-0.12.0) is causing test failures.
https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer/1801/workflows/c5177df1-1c6e-4146-a5f6-e4871c49f6bd

```
java.lang.IllegalArgumentException: Failed to register Collector of type MicrometerCollector: The Collector exposes the same name multiple times: my_timer_seconds
	at io.prometheus.client.CollectorRegistry.assertNoDuplicateNames(CollectorRegistry.java:71)
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:51)
	at io.prometheus.client.Collector.register(Collector.java:308)
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:479)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:475)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newLongTaskTimer(PrometheusMeterRegistry.java:288)
	at io.micrometer.core.instrument.MeterRegistry$More.lambda$longTaskTimer$0(MeterRegistry.java:884)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:620)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:569)
	at io.micrometer.core.instrument.MeterRegistry.access$600(MeterRegistry.java:78)
	at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:882)
	at io.micrometer.core.instrument.LongTaskTimer$Builder.register(LongTaskTimer.java:408)
	at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:872)
	at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:861)
```

**Comment by shakuzen** [comment]
This looks like a long standing issue with the implementation of the `describe` method for our `MicrometerCollector` for LongTaskTimers in the Prometheus registry. There are two `MetricFamilySamples` with the same name for `LongTaskTimer`, as opposed to the way the `Timer` and `DistributionSummary` description works: distinct `MetricFamilySamples`.
