### ISSUE TITLE
CgroupV1Subsystem causes NullPointerException

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#2800]
@PatrickGotthard reported this issue on Gitter (see [original message](https://gitter.im/spring-projects/spring-metrics?at=615458aaee6c260cf7ef1bbe)):

>Yesterday we migrated one of our non-productive Kubernetes clusters from dockershim to containerd. After that only one application refused to start with the following exception (shortened):
```
Caused by: java.lang.NullPointerException: null
    at java.base/java.util.Objects.requireNonNull(Unknown Source)
    at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
    at java.base/java.nio.file.Path.of(Unknown Source)
    at java.base/java.nio.file.Paths.get(Unknown Source)
    at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/jdk.internal.platform.CgroupUtil.readStringValue(Unknown Source)
    at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(Unknown Source)
    at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(Unknown Source)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(Unknown Source)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(Unknown Source)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(Unknown Source)
    at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getInstance(Unknown Source)
    at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(Unknown Source)
    at java.base/jdk.internal.platform.CgroupMetrics.getInstance(Unknown Source)
    at java.base/jdk.internal.platform.SystemMetrics.instance(Unknown Source)
    at java.base/jdk.internal.platform.Metrics.systemMetrics(Unknown Source)
    at java.base/jdk.internal.platform.Container.metrics(Unknown Source)
    at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(Unknown Source)
    at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(Unknown Source)
    at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(Unknown Source)
    at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(Unknown Source)
    at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(Unknown Source)
    at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(Unknown Source)
    at io.micrometer.core.instrument.binder.system.ProcessorMetrics.<init>(ProcessorMetrics.java:79)
    at io.micrometer.core.instrument.binder.system.ProcessorMetrics.<init>(ProcessorMetrics.java:74)
    at org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration.processorMetrics(SystemMetricsAutoConfiguration.java:53)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
    ... 94 common frames omitted
```
>The container image is build using the build-image goal of the spring-boot-maven-plugin without touching the default settings. Thus Liberica JDK 17 is packaged into the image. When downgrading to Java 11 the container starts without problems. It is also the only Java 17 application so far running in our K8s cluster.
The stacktrace and my tests indicate a JVM problem. For the moment disabling the SystemMetricsAutoConfiguration works, but I can't believe that I'm the only one with this particular problem.

Early investigation showed that [`ProcessorMetrics`](https://github.com/micrometer-metrics/micrometer/blob/55892ea27afb24fd60bea3ca42e214dddebc2f7f/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/ProcessorMetrics.java#L79) calls `ManagementFactory.getOperatingSystemMXBean()` in Micrometer so it is unlikely that this is a Micrometer issue and it is likely that the issue is in OpenJDK.

@PatrickGotthard  also found this issue in OpenJDK which seems to be the cause: https://bugs.openjdk.java.net/browse/JDK-8272124

**Comment by jonatan-ivanov** [comment]
Workaround: upgrade OpenJDK (when available see fixed versions in the issue above) or disable `SystemMetrics`.

**Comment by PatrickGotthard** [comment]
Hi @jonatan-ivanov,

yesterday we discovered that our cluster was misconfigured to use cgroups instead of systemd.
This issue/comment pointed us in the right direction: https://github.com/kubernetes/kubernetes/issues/103944#issuecomment-898267947
After fixing the cluster configuration the application works again without the need to disable the ProcessorMetrics :)

Regards,
Patrick

**Comment by mimmus** [comment]
Hi @PatrickGotthard ,
our cluster uses cgroup and there is no way to change to systemd in short times.
Any workaround for this issue?

**Comment by PatrickGotthard** [comment]
@mimmus upgrade your application to Java 18 or disable SystemMetricsAutoConfiguration -> I don't know whether other workarounds exist

**Comment by shakuzen** [comment]
The linked OpenJDK bug was also fixed in Java 8, 11, and 17 patch versions, so I believe the issue should be fixed if you are using the latest patch version.
