### ISSUE TITLE
Spring boot M7 doesn't compile with rc6 or rc7

### ISSUE THREAD

**Issue by srinivasvsk** [micrometer-metrics/micrometer#344]
Hi

Im having this error with M7,  not sure where it needs to be fixed , spring-boot vs micrometer

`Caused by: java.lang.NoSuchMethodError: io.micrometer.jmx.JmxMeterRegistry.<init>(Lio/micrometer/core/instrument/util/HierarchicalNameMapper;Lio/micrometer/core/instrument/Clock;)V
        at org.springframework.boot.actuate.autoconfigure.metrics.export.jmx.JmxExportConfiguration.lambda$jmxExporter$0(JmxExportConfiguration.java:43) ~[spring-boot-actuator-autoconfigure-2.0.0.M7.jar:2.0.0.M7]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_73]
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_73]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_73]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_73]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_73]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_73]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_73]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_73]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_73]
        at org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration.compositeMeterRegistry(MetricsAutoConfiguration.java:85) ~[spring-boot-actuator-autoconfigure-2.0.0.M7.jar:2.0.0.M7]
`

**Comment by jkschneider** [comment]
@srinivasvsk The signature of `JmxMeterRegistry` changed in rc7. It has been changed in the most recent snapshot for Boot 2 as well. It won't be possible to use JMX and Boot 2 M7 with Micrometer rc7.
