### ISSUE TITLE
Kafka Streams Metric Names Too Long.

### ISSUE THREAD

**Issue by mjallday** [micrometer-metrics/micrometer#3548]
**Describe the bug**
Adding metrics for kafka stream metrics results in errors about metric names being too long

```
[otel.javaagent 2022-11-28 19:31:16:302 +0000] [micrometer-kafka-metrics] WARN io.opentelemetry.ApiUsageLogging - Instrument name "kafka.stream.processor.node.window.aggregate.final.emit.latency.avg" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter. Returning noop instrument.
java.lang.AssertionError
    at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.log(ValidationUtil.java:55)
    at io.opentelemetry.javaagent.shaded.io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:72)
    at io.opentelemetry.sdk.metrics.SdkMeter.gaugeBuilder(SdkMeter.java:98)
    at io.opentelemetry.javaagent.shaded.instrumentation.micrometer.v1_5.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:37)
    at io.opentelemetry.javaagent.shaded.instrumentation.micrometer.v1_5.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:304)
    at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:563)
    at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:618)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:570)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:563)
    at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:304)
    at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:195)
    at io.micrometer.core.instrument.composite.CompositeGauge.registerNewMeter(CompositeGauge.java:57)
    at io.micrometer.core.instrument.composite.CompositeGauge.registerNewMeter(CompositeGauge.java:27)
    at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:68)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5700)
    at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:67)
    at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:189)
    at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:67)
    at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:627)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:570)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:563)
    at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:304)
    at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:195)
    at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.registerGauge(KafkaMetrics.java:262)
    at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.registerMeter(KafkaMetrics.java:256)
    at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.bindMeter(KafkaMetrics.java:246)
    at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.lambda$checkAndBindMetrics$5(KafkaMetrics.java:223)
    at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
    at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
    at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.checkAndBindMetrics(KafkaMetrics.java:187)
    at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.lambda$bindTo$0(KafkaMetrics.java:120)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment**

 - Micrometer version: 1.9.5
 - Micrometer registry: micrometer-registry-prometheus
 - OS: Docker
 - Java version: 
   openjdk version "17.0.4" 2022-07-19
   OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)
   OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing)

**To Reproduce**
How to reproduce the bug:

No specific steps. This appears to happen with Kafka Streams + Micrometer out of the box. 

Specific versions of these libraries

- org.springframework.cloud:spring-cloud-stream-binder-kafka-streams:jar:3.2.5
- org.apache.kafka:kafka-streams:jar:3.3.1
- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.4

**Expected behavior**
No error messages in logs and metric data for this particular metric

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by shakuzen** [comment]
Thanks for letting us know about the issue. According to the stack trace, it looks like it's the OpenTelemetry Java agent that is throwing that error, not Micrometer or the Prometheus SDK. Neither Micrometer nor Prometheus have such a limitation. Are you intentionally using the OpenTelemetry Java agent for metrics? I suspect disabling it would avoid this, if your goal is to expose the metrics in Prometheus format over the Spring Boot Actuator endpoint for Prometheus.

**Comment by mjallday** [comment]
Thanks, I'll go dig into that and re-open this issue if I discover this is relevant!
