### ISSUE TITLE
Getting errors from InfluxMeterRegistry even after disabling it

### ISSUE THREAD

**Issue by jainishan** [micrometer-metrics/micrometer#3574]
**Describe the bug**
I am using micrometer-core and micrometer-registry-influx version 1.9.5 (tried the latest one as well) in my spring boot application.

I started noticing the errors in every test case which conveyed issues with InfluxMeterRegistry

```
java.net.UnknownHostException: telegraf.system
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
    at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
    at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98)
    at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:305)
    at io.micrometer.influx.InfluxMeterRegistry.createDatabaseIfNecessary(InfluxMeterRegistry.java:111)
    at io.micrometer.influx.InfluxMeterRegistry.publish(InfluxMeterRegistry.java:123)
    at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54)
    at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:96)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:319)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156)
    at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
    at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
    at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
    at java.base/java.lang.Thread.run(Thread.java:833)
[influx-metrics-publisher] ERROR i.m.influx.InfluxMeterRegistry@createDatabaseIfNecessary:117  - unable to create database 'mydb'
java.net.UnknownHostException: telegraf.system
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
    at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
    at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98)
    at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:305)
    at io.micrometer.influx.InfluxMeterRegistry.createDatabaseIfNecessary(InfluxMeterRegistry.java:111)
    at io.micrometer.influx.InfluxMeterRegistry.publish(InfluxMeterRegistry.java:123)
    at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
[SpringApplicationShutdownHook] ERROR i.m.influx.InfluxMeterRegistry@publish:161  - failed to send metrics to influx
java.net.UnknownHostException: telegraf.system
    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
    at java.base/java.net.Socket.connect(Socket.java:633)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
    at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
    at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
    at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98)
    at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:305)
    at io.micrometer.influx.InfluxMeterRegistry.publish(InfluxMeterRegistry.java:147)
    at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54)
    at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:96)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:319)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156)
    at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
    at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
    at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
    at java.base/java.lang.Thread.run(Thread.java:833)
Disconnected from the target VM, address: '127.0.0.1:58220', transport: 'socket'

Process finished with exit code 0

```

I tried switching it off via application config:

```
management:
   metrics:
    export:
      influx:
        enabled: false
```

But just can't seem to get rid off these errors. I searched everywhere and switching off influx should have done it, but I am not sure why it keeps on coming. I tried adding a DB name here to see if the configuration is working and I would get that DB name in the error, so yeah the configs are getting picked up just fine.

**Environment**
Happening in spring boot integration tests. 
 - Micrometer version [1.9.5]
 - Micrometer registry [influx]
 - OS: [macOS, alpine]
 - Java version: [17]

**To Reproduce**
Disable exporting metrices to influx.
 
**Expected behavior**
There must be no errors related to exporting metrices to influx or creating the default 'mydb'.

**Additional context**
https://git.informatik.uni-hamburg.de/vsis-lehre/smartcities2020/dataspace/-/issues/82
https://github.com/micrometer-metrics/micrometer/issues/382

**Comment by jonatan-ivanov** [comment]
Please correct me if I'm wrong but I don't think this issue is in Micrometer. To me it seems either:
1. Spring Boot ignores the enable flag and this is a bug
2. You are using the wrong property (it changed in Boot 3.x, please check the Boot docs)
3. User config creates the registry not Boot that ignores the enable flag

You can check this by looking at/debugging the Spring Boot auto-configuration, reading the docs and checking your codebase if you create the registry on your own.
If you have proven that this is a Boot issue, please create an issue in the Spring Boot repository.

**Comment by jainishan** [comment]
Thanks for the response, I also now think the issue is somewhere else.
1. This seems likely. I added some debug points and looks like InfluxMeterRegistry is initialized with this flag enabled
2. Checked it several times and tried different combinations as well
3. Not sure what you mean here. I made sure there is no bean or configuration that could create this class

I will create a ticket in sprint boot maybe.

**Comment by arpita0104** [comment]
Hi team, I am getting below error while connecting to Victoria metrics using influxdb.2023-05-09T15:27:00.047-07:00 ERROR 10096 --- [trics-publisher] i.micrometer.influx.InfluxMeterRegistry  : unable to create database 'mydb'

java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:639) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1312) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1245) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1131) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1060) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1433) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1404) ~[na:na]
	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98) ~[micrometer-core-1.10.6.jar:1.10.6]
	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:306) ~[micrometer-core-1.10.6.jar:1.10.6]
	at io.micrometer.influx.InfluxMeterRegistry.createDatabaseIfNecessary(InfluxMeterRegistry.java:113) ~[micrometer-registry-influx-1.10.6.jar:1.10.6]
	at io.micrometer.influx.InfluxMeterRegistry.publish(InfluxMeterRegistry.java:125) ~[micrometer-registry-influx-1.10.6.jar:1.10.6]
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54) ~[micrometer-core-1.10.6.jar:1.10.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-09T15:27:01.009-07:00 ERROR 10096 --- [trics-publisher] i.micrometer.influx.InfluxMeterRegistry  : failed to send metrics to influx

**Comment by arpita0104** [comment]
I have a victoria metrics write end point to which I have to write my metrics using influxdb and this is the configuration I am using:
management.metrics.export.influx.enabled = true
management.metrics.export.influx.auto-create-db=false
management.endpoints.metrics.enabled = true
management.metrics.export.influx.uri=(Here I am passing victoria metrics write url)
management.endpoints.web.exposure.include=*

**Comment by arpita0104** [comment]
Can someone help with this issue.

**Comment by jonatan-ivanov** [comment]
Please see: https://github.com/micrometer-metrics/micrometer/issues/3574#issuecomment-1368540866

**Comment by jonatan-ivanov** [comment]
Oh , I just noticed:
```
management.metrics.export.influx.enabled = true
```
Could you please tell me what is the connection with your issue and this one? :o

**Comment by arpita0104** [comment]
My intention is to write to the victoria metrics end point and that is using influxdb. I am not sure which statement I should use
management.metrics.export.influx.enabled = true
management.metrics.export.influx.enabled = false 
but both are giving me the same error.

**Comment by arpita0104** [comment]
The same url I am able to connect from postman and able to write the data but from code it is giving me error.

**Comment by arpita0104** [comment]
I have added these dependencies in my pom.xml
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-core</artifactId>
		</dependency>

		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-influx</artifactId>
		</dependency>

**Comment by jonatan-ivanov** [comment]
To me is seems your issue is not related to the original one, please stop commenting this and open a new one with a minimal java reproducer.
