### ISSUE TITLE
TestObservationRegistry is not thread safe

### ISSUE THREAD

**Issue by marcingrzejszczak** [micrometer-metrics/micrometer#3653]
`TestObservationRegistry` registers a handler that is not thread safe.

```
java.util.ConcurrentModificationException: null
	at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1258) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at io.micrometer.observation.tck.TestObservationRegistry$ArrayListObservationHandler.onStop(TestObservationRegistry.java:87) ~[micrometer-observation-test-1.10.4.jar:1.10.4]
	at io.micrometer.observation.SimpleObservation.lambda$notifyOnObservationStopped$8(SimpleObservation.java:231) ~[micrometer-observation-1.10.4.jar:1.10.4]
```

**Comment by jonatan-ivanov** [comment]
Fixed in #3654
