### ISSUE TITLE
2023-04-11 03:08:01 1 ERROR --- [elastic-metrics-publisher] [,] i.m.elastic.ElasticMeterRegistry : failed to send metrics to elastic java.net.SocketTimeoutException: Connect timed out

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#3761]
**Describe the bug**
Hello Micrometer team,

I am currently using a SpringBoot app which:
1 - create some data and publish it inside elasticsearch using an elastic rest api endpoint, using Netty WebClient
2 - publish application metrics to elastic as well using micrometer-registry-elastic and those configurations:

```
management.elastic.metrics.export.auto-create-index=false
management.elastic.metrics.export.enabled=true
management.elastic.metrics.export.host=my-secure-https-elastic.com
management.elastic.metrics.export.index=myindex
management.elastic.metrics.export.indexDateFormat=yyyy-MM
```

Around 40% of the time, we are seeing this issue:

```
2023-04-11 03:15:01 1 ERROR --- [elastic-metrics-publisher] [,] i.m.elastic.ElasticMeterRegistry : failed to send metrics to elastic
java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
        at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98)
        at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:306)
        at io.micrometer.elastic.ElasticMeterRegistry.publish(ElasticMeterRegistry.java:129)
        at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

To add clarification, we are not seeing any timeout for use case 1 (where we use a Netty WebClient to send business data to elasticsearch)

Looking at this: https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java#L396 it seems there are ways to set connect time out and read time out but NOT socket time out.

We bumped those to crazy values, still seeing this issue.

Could you please help on this issue?

Thank you

**Environment**

 - Micrometer version 1.11.0-M2
 - Micrometer registry elastic
 - OS: issue Linux
 - Java version: 17

**Expected behavior**
Not seeing ``` failed to send metrics to elastic java.net.SocketTimeoutException: Connect timed out```

**Comment by jonatan-ivanov** [comment]
Read timeout should be the same what you call socket timeout (time between receiving a chunk of data). Also, you get `Connect timed out`, so you should increase the `connectTimeout`.

You can verify this with `telnet`. Also, this indicates that maybe your network/elasticsearch cluster has some issues.
Also, the fact that this happens 40% of the time tells me that there might be a max connections limit somewhere.

Is this happening with the latest 1.10.x too or just 1.11.0-M2?

**Comment by patpatpat123** [comment]
Thank you for your answer @jonatan-ivanov,

I took both 1.10.x and 1.11.0-M2, reproducible with both, therefore, I think it is ok to rule out a possible regression.

Adding to that, I did some additional analysis.
We believed (I think by mistake) the properties to control the time out are:

```
management.elastic.metrics.export.readTimeout=10s
management.elastic.metrics.export.connectTimeout=10s
```
I think the above properties we are using are not correct.

With that said, we took the repo, and hardcoded changes here and here:

https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushRegistryConfig.java#L71

Changing to 
```
return (Duration)PropertyValidator.getDuration(this, "connectTimeout").orElse(Duration.ofSeconds(100L));

return (Duration)PropertyValidator.getDuration(this, "readTimeout").orElse(Duration.ofSeconds(100L));
```

And repackaged the whole thing.

It seems with this new hardcoded value, the issue is resolved.

Therefore, may I ask:

- Would it be possible to suggest the correct property names to act on the time out?
- Would it make sense to start a PR bumping the values of the time out, or at least, making them the same at 10s?

Thank you

**Comment by bclozel** [comment]
@patpatpat123 
Did you try with those configuration properties:
* [`management.elastic.metrics.export.connect-timeout`](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.actuator.management.elastic.metrics.export.connect-timeout)
* [`management.elastic.metrics.export.read-timeout`](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.actuator.management.elastic.metrics.export.read-timeout)
