### ISSUE TITLE
Spring boot webflux app performance degradation due to micrometer tracing

### ISSUE THREAD

**Issue by lazysasha** [micrometer-metrics/micrometer#3858]
**Describe the bug**
Hi all, we have noticed significant performance degradation with our Spring Boot `3.0.7` application that uses Micrometer `1.10.7`.

**Environment**

- Spring boot version [3.0.7]
 - Micrometer version [1.10.7]
 - Micrometer registry [prometheus]
 - OS: Debian GNU/Linux 11 (docker container running on k8s)
 - Java version: Zulu17.42+19-CA

**To Reproduce**
How to reproduce the bug:
We reproduce it by running a performance (locust with 128 users) test on a spring webflux app (3.0.7) with micrometer tracing enabled (`management.tracing.enabled` set to `true`). The app simply receives api requests, makes external api calls, processes the response and returns the result.

**Expected behaviour**
On this version rps goes down to ~400 vs. 1.7K on previous version with spring boot `3.0.5` and micrometer `1.10.5`.
Also, pods are constantly changing their readiness status due to a portion of failing readiness checks (no restarts though):
```shell
my-deployment-7c7748ddb4-xvst2                                  2/2     Running           0          16m
my-deployment-7c7748ddb4-5rk9t                                  1/2     Running           0          14m
my-deployment-7c7748ddb4-5rk9t                                  2/2     Running           0          14m
my-deployment-7c7748ddb4-xvst2                                  1/2     Running           0          16m
my-deployment-7c7748ddb4-xvst2                                  2/2     Running           0          16m
my-deployment-7c7748ddb4-5rk9t                                  1/2     Running           0          15m
my-deployment-7c7748ddb4-5rk9t                                  2/2     Running           0          15m
```

**Additional context**
Analysis of thread dump shows that work related to `Slf4JBaggageEventListener` often occupies all 4 `reactor-http-epoll-*` working threads of the app, leaving almost no room for doing actual work to process the user and readiness check requests:
```java
"reactor-http-epoll-4" - Thread t@52
   java.lang.Thread.State: RUNNABLE
        at app//io.micrometer.tracing.otel.bridge.Slf4JBaggageEventListener$$Lambda$2160/0x0000000801e06108.accept(Unknown Source)
        at java.base@17.0.7/java.util.ArrayList.forEach(ArrayList.java:1511)
        at app//io.micrometer.tracing.otel.bridge.Slf4JBaggageEventListener.onScopeClosed(Slf4JBaggageEventListener.java:85)
        at app//io.micrometer.tracing.otel.bridge.Slf4JBaggageEventListener.onEvent(Slf4JBaggageEventListener.java:94)
        at app//org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration$OTelEventPublisher.publishEvent(OpenTelemetryAutoConfiguration.java:248)
        at app//io.micrometer.tracing.otel.bridge.EventPublishingContextWrapper$1.lambda$attach$0(EventPublishingContextWrapper.java:57)
        at app//io.micrometer.tracing.otel.bridge.EventPublishingContextWrapper$1$$Lambda$2149/0x0000000801dfed10.close(Unknown Source)
        at app//io.micrometer.tracing.otel.bridge.OtelCurrentTraceContext$$Lambda$2150/0x0000000801dfef58.close(Unknown Source)
        at app//io.micrometer.tracing.handler.RevertingScope.close(RevertingScope.java:39)
        at app//io.micrometer.tracing.handler.TracingObservationHandler.onScopeReset(TracingObservationHandler.java:110)
        at app//io.micrometer.observation.ObservationHandler$FirstMatchingCompositeObservationHandler.onScopeReset(ObservationHandler.java:189)
        at app//io.micrometer.observation.SimpleObservation.notifyOnScopeReset(SimpleObservation.java:278)
        at app//io.micrometer.observation.SimpleObservation.access$200(SimpleObservation.java:38)
        at app//io.micrometer.observation.SimpleObservation$SimpleScope.reset(SimpleObservation.java:331)
        at app//io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.reset(ObservationThreadLocalAccessor.java:58)
        at app//io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:64)
        at app//io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:28)
```

Another test with  `management.tracing.enabled` set to true, but `management.tracing.baggage.correlation.enabled` set to `false`  pods readiness status stays stable, but the rps is still twice less comparing to a previous version having it enabled (~900 vs. 1.7K). This time same threads are often busy with handling micrometer observations:
```java
"reactor-http-epoll-1" - Thread t@49
   java.lang.Thread.State: RUNNABLE
        at app//io.micrometer.tracing.handler.RevertingScope.close(RevertingScope.java:40)
        at app//io.micrometer.tracing.handler.TracingObservationHandler.onScopeReset(TracingObservationHandler.java:110)
        at app//io.micrometer.observation.ObservationHandler$FirstMatchingCompositeObservationHandler.onScopeReset(ObservationHandler.java:189)
        at app//io.micrometer.observation.SimpleObservation.notifyOnScopeReset(SimpleObservation.java:278)
        at app//io.micrometer.observation.SimpleObservation.access$200(SimpleObservation.java:38)
        at app//io.micrometer.observation.SimpleObservation$SimpleScope.reset(SimpleObservation.java:331)
        at app//io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.reset(ObservationThreadLocalAccessor.java:58)
        at app//io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:64)
        at app//io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:28)
        at app//reactor.core.publisher.ContextPropagation$ReactorScopeImpl.resetThreadLocalValue(ContextPropagation.java:503)
        at app//reactor.core.publisher.ContextPropagation$ReactorScopeImpl.close(ContextPropagation.java:495)
        at app//reactor.core.publisher.MonoContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.onSubscribe(MonoContextWriteRestoringThreadLocals.java:96)
        at app//reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
```

Highly appreciated if someone can have a look at it. I am happy to help with testing and investigation.

**Comment by jonatan-ivanov** [comment]
Thanks for reporting this.
I have a few questions to narrow this down:

1. The app with Boot 3.0.5 and Micrometer 1.10.5 had tracing enabled as well?
2. What happens if you stay on Boot 3.0.5 but upgrade Micrometer to 1.10.7 (and Micrometer Tracing to 1.0.6)?
3. Or what happens if you upgrade to Boot 3.0.7 but stay on Micrometer 1.10.5 (and Micrometer Tracing to 1.0.3)? (With these two I'm trying to see if a change in Micrometer or in Boot caused this)
4. What happens if instead of OTel you use the Brave bridge (you can also check what happens without the exporter)? (With this, I'm trying to figure out if a change in Micrometer or in OTel caused this)

**Comment by lazysasha** [comment]
1 - Yes, tracing was enabled on Boot 3.0.5 and Micrometer 1.10.5, performance was fine
2, 3, 4 - I'll run performance tests for these use cases and will get back to you.

**Comment by jonatan-ivanov** [comment]
Thank you very much for checking!

Based on this, this is likely caused by `micrometer-tracing-bridge-otel` somewhere [between 1.0.3 and 1.0.6](https://github.com/micrometer-metrics/tracing/compare/v1.0.3...v1.0.6) since:
- The **old Boot** version with the **old Micrometer** version is **ok**
- The **new Boot** version with the **old Micrometer** version is **ok**
- The **old Boot** version with the **new Micrometer** version is **degraded**
- The Brave bridge seems ok, so I would assume it's the OTel Bridge. `Slf4JBaggageEventListener` seemingly being the bottleneck agrees with this though we don't have a base-line for Brave, there is a slight chance that the cause is not in the bridge but somewhere above and the path with Brave is also degraded it is just that more performant.

I think there might be two possible workarounds for you in the meantime we investigate this:
1. If your backend supports the Zipkin format (Zipkin, Jaeger, many other backends), try to move to the Brave Bridge. If you need extra (OTel-related) tags, you can add them using a `SpanFilter`.
2. If your backend does not support the Zipkin format (i.e.: OTLP-only) or you want to use the OTel SDK for some reason, try to force Micrometer Tracing 1.0.4 or 1.0.3 (we made a mistake with the 1.0.5 release) and only upgrade to the new Boot and Micrometer versions.

You already helped a lot but if you want to try downgrading only Micrometer Tracing (1.0.4 or 1.0.3), could you please tell us the outcome? This could help narrowing even further the issue.

**Comment by lazysasha** [comment]
Thanks for your analysis.
I've ran another performance test with spring boot 3.0.7, micrometer 1.10.7, micrometer-tracing-bridge-otel 1.0.6 and micrometer-tracing 1.0.3 and I see performance decrease as well, this time to ~800rps, sometimes getting down to ~400rps and readiness status check changing again.

**Comment by jonatan-ivanov** [comment]
There are a few moving components there so could you please check what happens when all versions of Micrometer Tracing is the same?
So micrometer-tracing 1.0.3 and micrometer-tracing-bridge-otel 1.0.3 but keep Spring Boot at 3.0.7 and Micrometer at 1.10.7.

**Comment by lazysasha** [comment]
> micrometer-tracing 1.0.3 and micrometer-tracing-bridge-otel 1.0.3 but keep Spring Boot at 3.0.7 and Micrometer at 1.10.7.

With this setup I see the performance falling down to 800rps, but pods keep on running without any restarts or readines status changes.

**Comment by marcingrzejszczak** [comment]
Can you check this against latest release versions? We've introduced various performance improvements

**Comment by lazysasha** [comment]
Sure, will give it a try and let you know the result asap
