### ISSUE TITLE
ConcurrentModificationException on Observation$Context.computeIfAbsent

### ISSUE THREAD

**Issue by ghenadiibatalski** [micrometer-metrics/micrometer#3874]
**Describe the bug**
In some circumstances the ConcurrentModificationException occurs while calling `Observation$Context.computeIfAbsent`.  I think, a switch to the `ConcurrentHashMap` for 

https://github.com/micrometer-metrics/micrometer/blob/ef78705197903773f5b3550920c933c7c2b2d3ec/micrometer-observation/src/main/java/io/micrometer/observation/Observation.java#LL867C44-L867C44

could solve the problem. The error occurs at the spring boot application start.

Regards, Gena

```
{
    "@timestamp": "2023-06-02T14:48:12.234Z",
    "@version": "1",
    "message": "Operator called default onErrorDropped",
    "logger_name": "reactor.core.publisher.Operators",
    "thread_name": "reactor-http-epoll-3",
    "level": "ERROR",
    "level_value": 40000,
    "stack_trace": "java.util.ConcurrentModificationException: null
at java.util.HashMap.computeIfAbsent(HashMap.java:1221)
at io.micrometer.observation.Observation$Context.computeIfAbsent(Observation.java:982)
at i.m.tracing.handler.TracingObservationHandler.getTracingContext(TracingObservationHandler.java:182)
at i.m.t.handler.DefaultTracingObservationHandler.onStart(DefaultTracingObservationHandler.java:45)
at i.m.o.ObservationHandler$FirstMatchingCompositeObservationHandler.onStart(ObservationHandler.java:149)
at io.micrometer.observation.SimpleObservation.notifyOnObservationStarted(SimpleObservation.java:232)
at io.micrometer.observation.SimpleObservation.start(SimpleObservation.java:167)
at o.s.s.w.s.ObservationWebFilterChainDecorator$AroundWebFilterObservation$SimpleAroundWebFilterObservation$ObservationReference.start(ObservationWebFilterChainDecorator.java:395)
at o.s.s.w.s.ObservationWebFilterChainDecorator$AroundWebFilterObservation$SimpleAroundWebFilterObservation.start(ObservationWebFilterChainDecorator.java:276)
at r.c.p.FluxPeekFuseable$PeekFuseableConditionalSubscriber.cancel(FluxPeekFuseable.java:445)
at r.c.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
at r.c.p.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)
at r.c.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
at r.c.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
at r.c.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
at r.c.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
at r.c.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
at r.c.p.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2399)
at r.c.p.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2367)
at r.c.p.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2179)
... 127 frames truncated\n",
    "spanId": "693e79b807fba7c9",
    "traceId": "647a012c59985753f041cacd8a706631",
    "stack_hash": "5e040fc1"
}

```
**Environment**

 - OS: linux, k8s
 - Java version: 17
- Spring boot 3.0.7
- Micrometer Observation 1.10.7

**To Reproduce**
How to reproduce the bug:

didn't do something special, just started the application

**Expected behavior**
The mentioned exception doesn't occur
**Additional context**
spring boot 3.0.7 reactive application

**Comment by bclozel** [comment]
Could you share a minimal, sample application that replicates the issue? I'm wondering which instrumentation is being recorded at startup and why there are concurrent calls on a single observation.

Thanks!

**Comment by axelmyrbergtsab** [comment]
I also got this exception:

`"java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at io.micrometer.observation.Observation$Context.computeIfAbsent(Observation.java:1036)
	at io.micrometer.tracing.handler.TracingObservationHandler.getTracingContext(TracingObservationHandler.java:179)
	at io.micrometer.tracing.handler.TracingObservationHandler.onScopeOpened(TracingObservationHandler.java:79)
	at io.micrometer.observation.ObservationHandler$FirstMatchingCompositeObservationHandler.onScopeOpened(ObservationHandler.java:173)
	at io.micrometer.observation.SimpleObservation.notifyOnScopeOpened(SimpleObservation.java:243)
	at io.micrometer.observation.SimpleObservation.openScope(SimpleObservation.java:202)
	at org.springframework.security.web.server.ObservationWebFilterChainDecorator$AroundWebFilterObservation$SimpleAroundWebFilterObservation.openScope(ObservationWebFilterChainDecorator.java:333)
	at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.setValue(ObservationThreadLocalAccessor.java:109)
	at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.setValue(ObservationThreadLocalAccessor.java:32)
	at io.micrometer.context.DefaultContextSnapshot.setThreadLocal(DefaultContextSnapshot.java:102)
	at io.micrometer.context.DefaultContextSnapshotFactory.setAllThreadLocalsFrom(DefaultContextSnapshotFactory.java:125)
	at io.micrometer.context.DefaultContextSnapshotFactory.setThreadLocalsFrom(DefaultContextSnapshotFactory.java:109)
	at reactor.core.publisher.ContextPropagation.setThreadLocals(ContextPropagation.java:74)
	at reactor.core.publisher.MonoContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.cancel(MonoContextWriteRestoringThreadLocals.java:163)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.cancel(MonoFlatMap.java:207)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.cancel(FluxDoOnEach.java:113)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:153)
	at reactor.core.publisher.MonoContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.cancel(MonoContextWriteRestoringThreadLocals.java:164)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2399)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2367)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2179)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2399)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2367)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2179)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2399)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2367)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2179)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2399)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2367)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2179)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2399)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2367)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2179)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.cancel(MonoIgnoreThen.java:143)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.cancel(MonoPeekTerminal.java:144)
	at reactor.core.publisher.Operators.terminate(Operators.java:1277)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:481)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)`

After running the application for a while.

After this error, the application is "stuck" on the same traceId, never generating a new one. Using micrometer tracing 1.1.4

**Comment by axelmyrbergtsab** [comment]
No sorry I'm afraid not, I've only seen this in production logs and haven't been able to reproduce it.

**Comment by ghenadiibatalski** [comment]
@marcingrzejszczak same here: occurs from time to time in a cluster. Should it possibly be a ConcurrentHashMap?

**Comment by axelmyrbergtsab** [comment]
@marcingrzejszczak Could this be related? The stacktrace looks very similar but not identical:
https://github.com/micrometer-metrics/tracing/issues/357
