### ISSUE TITLE
Micrometer with <1.5 seconds step size no longer sends metrics to Influx in version 1.11.0

### ISSUE THREAD

**Issue by atennapel** [micrometer-metrics/micrometer#3879]
**Describe the bug**
We have an automated test that uses Micrometer to sends some metrics to Influx. We had the step configured to 100ms so that the test can run quickly.
Since we updated to Micrometer 1.11.0 this test was failing and with some experimentation I found that I had to change the step size to at least 1.5 seconds before the test works again.
Did something change in 1.11.0 that could have affected this behavior for Micrometer with Influx?

**Environment**
Java 11, Micrometer 1.11.0.

**To Reproduce**
The test works like this:
1. Start InfluxDB (using https://www.testcontainers.org/)
2. Use Micrometer to send a timer metric (step size 100ms)
3. Periodically query the Influx database until the metric is found

**Expected behavior**
Metrics should be send to Influx, with a step of 100ms.

**Comment by lenin-jaganathan** [comment]
@shakuzen This might be related to this PR https://github.com/micrometer-metrics/micrometer/pull/3750.

**Comment by atennapel** [comment]
With 1.12.4 and step size 100ms, I get:
```
[2024-03-15T08:05:11.122Z] 2024-03-15 09:05:11.112 ERROR - io.micrometer.influx.InfluxMeterRegistry: failed to send metrics to influx
[2024-03-15T08:05:11.122Z] java.net.ConnectException: Connection refused
[2024-03-15T08:05:11.122Z] 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[2024-03-15T08:05:11.122Z] 	at java.base/java.net.Socket.connect(Socket.java:633)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
[2024-03-15T08:05:11.122Z] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
[2024-03-15T08:05:11.122Z] 	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:98)
[2024-03-15T08:05:11.122Z] 	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:306)
[2024-03-15T08:05:11.122Z] 	at io.micrometer.influx.InfluxMeterRegistry.publish(InfluxMeterRegistry.java:149)
[2024-03-15T08:05:11.122Z] 	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafelyOrSkipIfInProgress(PushMeterRegistry.java:64)
[2024-03-15T08:05:11.122Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-03-15T08:05:11.122Z] 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2024-03-15T08:05:11.122Z] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2024-03-15T08:05:11.122Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-03-15T08:05:11.122Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-03-15T08:05:11.122Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by shakuzen** [comment]
Connection refused means the Influx server is refusing the new connection. Perhaps too many connections are being established at once?
