### ISSUE TITLE
 Failed to register Collector of type MicrometerCollector: some_name_timer_seconds_count is already in use by another Collector of type MicrometerCollector

### ISSUE THREAD

**Issue by ckiatng** [micrometer-metrics/micrometer#4045]
**Describe the bug**
In my code, I try to create a Timer metric with following code:
`Timer.builder("some_name")`
`    .publishPercentiles(0.5, 0.75, 0.95, 0.98, 0.99, 0.999)`
`    .distributionStatisticExpiry(Duration.ofMinutes(1L))`
`    .register(meterRegistry);`

I am using PrometheusMeterRegistry with very default configuration
`PrometheusMeterRegistry prometheusMeterRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT, CollectorRegistry.defaultRegistry, Clock.SYSTEM);`

Most of the time my application will start successfully with the metrics available. However in some random scenario where I believe there is a race condition happening to register the Timer metric for the first time, my application will fail to start with following Exception:
> ...:  java.lang.IllegalArgumentException: Failed to register Collector of type MicrometerCollector: some_name_timer_seconds_count is already in use by another Collector of type MicrometerCollector
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:57)
	at io.prometheus.client.Collector.register(Collector.java:307)
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$17(PrometheusMeterRegistry.java:557)
	at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:552) [1 skipped]
	at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:318)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:325)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:625)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:577)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
	at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:205)
	at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:35)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:68)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:67) [2 skipped]
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:189)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:67)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:634)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:577)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
	...

It seems that even though `MeterRegistry.getOrCreateMeter(...)` already handled **double check locking** to prevent the same Timer being registered twice, however the above exception still happened.

**Environment**
 - Micrometer version 1.11.1
 - Prometheus_simpleclient version: 0.16.0
 - Micrometer registry (Prometheus)
 - OS: Ubuntu
 - Java version: 17

**To Reproduce**
Happen when there is a race condition.

**Expected behavior**
During race condition, only 1 Timer metric should be registered.

**Additional context**
I learned from other issues that this could be an issue with CollectorRegistry not clear or remove the meter properly. However this still required verification.

**Comment by ckiatng** [comment]
After investigation, I realised that the problem happened due to multiple `PrometheusMeterRegistry` sharing the same `CollectorRegistry.defaultRegistry`. This situation happened when there is a race condition to instantiate `PrometheusMeterRegistry` and adding them to the CompositeMeterRegistry of `Metrics.globalRegistry`.

**Comment by raju-gundu-techbulls** [comment]
I am aslo facing this issue, what changes did you make to resolve it
