### ISSUE TITLE
Disable Java ToolChain auto-provisioning

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#4067]
Theoretically we should use the same version to run the gradle process as the version we use for compiling so there is no need for auto-provisioning at the moment and calling FooJay's DISCO API which seems to be down right now and fails our build:

```
Execution failed for task ':micrometer-jetty11:downloadDependencies'.
> Could not resolve all dependencies for configuration ':micrometer-jetty11:compileClasspath'.
   > Failed to calculate the value of task ':micrometer-core:compileJava11Java' property 'javaCompiler'.
      > Requesting vendor list failed: <html>
        <head><title>503 Service Temporarily Unavailable</title></head>
        <body>
        <center><h1>503 Service Temporarily Unavailable</h1></center>
        <hr><center>nginx</center>
        </body>
        </html>

at org.gradle.toolchains.foojay.FoojayApi.readResponse(FoojayApi.kt:117)	
at org.gradle.toolchains.foojay.FoojayApi.fetchDistributionsIfMissing(FoojayApi.kt:59)	
at org.gradle.toolchains.foojay.FoojayApi.match$foojay_resolver(FoojayApi.kt:49)	
at org.gradle.toolchains.foojay.FoojayApi.toLinks(FoojayApi.kt:41)	
at org.gradle.toolchains.foojay.FoojayToolchainResolver.resolve(FoojayToolchainResolver.kt:15)	
at org.gradle.jvm.toolchain.internal.install.DefaultJavaToolchainProvisioningService.tryInstall(DefaultJavaToolchainProvisioningService.java:114)
```

See: https://ge.micrometer.io/s/grimzzdzyoo7w/failure?expanded-stacktrace=WyIwLTMtNi04Il0

**Comment by shakuzen** [comment]
We are not able to disable auto-provisioning on our CI builds due to the multi-release jar plugin requiring the exact JDK version as the targetVersion. I've opened https://github.com/melix/mrjar-gradle-plugin/issues/7 to see if that can be relaxed. Ideally, we don't want to auto-provision Java/JDK versions on CI.
