### ISSUE TITLE
StackoverflowError while using micrometer-spring-legacy alongwith StatsD registry

### ISSUE THREAD

**Issue by aarya23** [micrometer-metrics/micrometer#411]
getting into recursion as Counter.increment call results in **MetricsTurboFilter** invoking **Counter.increment** again.

Additional configuration in the springboot app:

  ```
<dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-spring-legacy</artifactId>
            <version>1.0.0-rc.7</version>
        </dependency>

 <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-statsd</artifactId>
            <version>1.0.0-rc.7</version>
        </dependency>

        <reactor.version>3.1.0.RELEASE</reactor.version>
        <spring.boot.version>1.5.4.RELEASE</spring.boot.version>
```

**StackoverlfowError:**

	at io.micrometer.core.instrument.Counter.increment(Counter.java:30)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:102)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.debug(Logger.java:482)
	at reactor.util.Loggers$Slf4JLogger.debug(Loggers.java:213)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:282)
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:317)
	**at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:43)**
	at io.micrometer.core.instrument.composite.CompositeCounter.lambda$increment$0(CompositeCounter.java:31)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.lambda$forEachChild$0(AbstractCompositeMeter.java:50)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:50)
	at io.micrometer.core.instrument.composite.CompositeCounter.increment(CompositeCounter.java:31)
	at io.micrometer.core.instrument.Counter.increment(Counter.java:30)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:102)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.debug(Logger.java:482)
	at reactor.util.Loggers$Slf4JLogger.debug(Loggers.java:213)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:282)
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:317)
	**at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:43)**
	at io.micrometer.core.instrument.composite.CompositeCounter.lambda$increment$0(CompositeCounter.java:31)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.lambda$forEachChild$0(AbstractCompositeMeter.java:50)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:50)
	at io.micrometer.core.instrument.composite.CompositeCounter.increment(CompositeCounter.java:31)
	at io.micrometer.core.instrument.Counter.increment(Counter.java:30)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:102)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.debug(Logger.java:482)
	at reactor.util.Loggers$Slf4JLogger.debug(Loggers.java:213)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:282)
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:317)
	**at io.micrometer.statsd.StatsdCounter.increment(StatsdCounter.java:43)**
	at io.micrometer.core.instrument.composite.CompositeCounter.lambda$increment$0(CompositeCounter.java:31)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.lambda$forEachChild$0(AbstractCompositeMeter.java:50)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:50)
	at io.micrometer.core.instrument.composite.CompositeCounter.increment(CompositeCounter.java:31)
	at io.micrometer.core.instrument.Counter.increment(Counter.java:30)
	at io.micrometer.core.instrument.binder.logging.MetricsTurboFilter.decide(LogbackMetrics.java:102)
	at ch.qos.logback.classic.spi.TurboFilterList.getTurboFilterChainDecision(TurboFilterList.java:49)
	at ch.qos.logback.classic.LoggerContext.getTurboFilterChainDecision_0_3OrMore(LoggerContext.java:269)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:373)
	at ch.qos.logback.classic.Logger.debug(Logger.java:482)
	at reactor.util.Loggers$Slf4JLogger.debug(Loggers.java:213)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:282)
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:317)

**Comment by jkschneider** [comment]
Good catch, thanks!
