### ISSUE TITLE
ObservationExecChainHandlerIntegrationTest.ClassicClient#recordSocketTimeoutAsIoErrors is flaky

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#4568]
See, for example, https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer/5582/workflows/640e36d2-2559-49d3-86d3-dc15add14a00/jobs/28480/tests#failed-test-0

```
java.lang.AssertionError: 
Expecting code to raise a throwable.
	at io.micrometer.core.instrument.binder.httpcomponents.hc5.ObservationExecChainHandlerIntegrationTest$ClassicClient.recordSocketTimeoutAsIoErrors(ObservationExecChainHandlerIntegrationTest.java:179)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by shakuzen** [comment]
Reopening to backport to `1.12.x` branch since it is flaky there too. https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer/5592/workflows/3b4e138d-1d74-4305-8727-766d964a351a/jobs/28523/tests#failed-test-0
