### ISSUE TITLE
MongoMetricsCommandListenerTest.shouldCreateFailedCommandMetricWithCustomSettings() seems flaky

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#4602]
It failed on CI as follows:

```
MongoMetricsCommandListenerTest > shouldCreateFailedCommandMetricWithCustomSettings() FAILED
    io.micrometer.core.instrument.search.MeterNotFoundException: Unable to find a meter that matches all the requirements at once. Here's what was found:
       OK: A meter with name 'mongodb.driver.commands' was found.
       OK: A meter with type timer was found.
       FAIL: No meters have a tag 'cluster.id' with value '65aa84157856c446e440099e'. The only value found was '65aa84157856c446e440099f'.
       OK: A meter with name 'mongodb.driver.commands' has a tag 'collection' with value 'testCol'.
       OK: A meter with name 'mongodb.driver.commands' has a tag 'command' with value 'dropIndexes'.
       OK: A meter with name 'mongodb.driver.commands' has a tag 'mongoz' with value '5150'.
       OK: A meter with name 'mongodb.driver.commands' has a tag 'server.address' with value 'localhost:32781'.
       OK: A meter with name 'mongodb.driver.commands' has a tag 'status' with value 'FAILED'.
        at app//io.micrometer.core.instrument.search.MeterNotFoundException$FromRequiredSearch.build(MeterNotFoundException.java:245)
        at app//io.micrometer.core.instrument.search.MeterNotFoundException$FromRequiredSearch.access$100(MeterNotFoundException.java:49)
        at app//io.micrometer.core.instrument.search.MeterNotFoundException.forSearch(MeterNotFoundException.java:46)
        at app//io.micrometer.core.instrument.search.RequiredSearch.lambda$getOne$1(RequiredSearch.java:199)
        at java.base@17.0.8.1/java.util.Optional.orElseThrow(Optional.java:403)
        at app//io.micrometer.core.instrument.search.RequiredSearch.getOne(RequiredSearch.java:199)
        at app//io.micrometer.core.instrument.search.RequiredSearch.timer(RequiredSearch.java:120)
        at app//io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListenerTest.shouldCreateFailedCommandMetricWithCustomSettings(MongoMetricsCommandListenerTest.java:140)
```

See https://github.com/micrometer-metrics/micrometer/pull/4600 and https://app.circleci.com/pipelines/github/micrometer-metrics/micrometer/5674/workflows/8ce0e4c3-f79f-4e53-b4ff-9615de58cd4b/jobs/28908

**Comment by etrandafir93** [comment]
hello @shakuzen, @izeye - I took a look over this one. 
As far as I can see, other tests from this class can be flaky, too.

In the `@BeforeEach` block, we create a new mongo client and set the `clusterId` field of the test class (asynchronously, via the _ClusterOpeningEvent_ listener).

This can be a problem on its own, because if the field is not set fast enough, the test can start without it. We can reproduce this by adding a small delay in the _clusterListener_:

```java
@BeforeEach
void setup() {
    clusterId = new AtomicReference<>();
    // tag::setup[]
    registry = new SimpleMeterRegistry();
    MongoClientSettings settings = MongoClientSettings.builder()
        .addCommandListener(new MongoMetricsCommandListener(registry))
        .applyToClusterSettings(builder -> builder.hosts(singletonList(new ServerAddress(host, port)))
            .addClusterListener(new ClusterListener() {
                @Override
                public void clusterOpening(ClusterOpeningEvent event) {
                    sleep(100); // <- artificial delay to reproduce the issue
                    clusterId.set(event.getClusterId().getValue());
                }
            }))
        .build();
    mongo = MongoClients.create(settings);
    // end::setup[]
}

@Test
void shouldCreateSuccessCommandMetric() {
    // ...
    assertThat(clusterId.get()).isNotNull(); // <- when the test starts before the clusterListener, it will fail
    // ...
}
```

----

The problem described in this issue is pretty similar. There are two tests that are creating yet another mongo client:
- shouldCreateFailedCommandMetricWithCustomSettings()
- shouldCreateSuccessCommandMetricWithCustomSettings() 

The creation of these additional mongo clients with custom settings is pretty similar to what we have in the `BeforeEach` - meaning that this code, too, tries to set the `clusterId` as a field for the test class. 

Therefore, we have a race condition between the first mongo client (created in beforeEach) and the 2nd mongo client (created at the beginning of the test). Both of them are trying to asynchronously set the same clusterId field, and the fact that we've declared it as an _AtomicReference_ won't solve the issue.

If we add a short artificial delay to the 2nd client we'll get tha exact same error message:

```java
@BeforeEach
void setup() {
    clusterId = new AtomicReference<>();
    // tag::setup[]
    registry = new SimpleMeterRegistry();
    MongoClientSettings settings = MongoClientSettings.builder()
        .addCommandListener(new MongoMetricsCommandListener(registry))
        .applyToClusterSettings(builder -> builder.hosts(singletonList(new ServerAddress(host, port)))
            .addClusterListener(new ClusterListener() {
                @Override
                public void clusterOpening(ClusterOpeningEvent event) {
                    clusterId.set(event.getClusterId().getValue());
                }
            }))
        .build();
    mongo = MongoClients.create(settings);
    // end::setup[]
}

@Test
void shouldCreateFailedCommandMetricWithCustomSettings() {
    MongoCommandTagsProvider tagsProvider = ...
    MongoClientSettings settings = MongoClientSettings.builder()
        .addCommandListener(new MongoMetricsCommandListener(registry, tagsProvider))
        .applyToClusterSettings(builder -> builder.hosts(singletonList(new ServerAddress(host, port)))
            .addClusterListener(new ClusterListener() {
                @Override
                public void clusterOpening(ClusterOpeningEvent event) {
                    sleep(100); // <-- artificial delay to reproduce the issue
                    clusterId.set(event.getClusterId().getValue());
                }
            }))
        .build();

    try (MongoClient mongo = MongoClients.create(settings)) {
        mongo.getDatabase("test").getCollection("testCol").dropIndex("nonExistentIndex");
        assertThat(clusterId.get()).isNotNull();
        // ...
        assertThat(registry.get("mongodb.driver.commands").tags(tags).timer().count()).isEqualTo(1);
       //    the cluster id now points to the mongo client created in the BeforeEach block, 
       //               not to the one created by the test
    }
}
```
This reproduces the build error:

```plaintext
Unable to find a meter that matches all the requirements at once. Here's what was found:
   OK: A meter with name 'mongodb.driver.commands' was found.
   OK: A meter with type timer was found.
   FAIL: No meters have a tag 'cluster.id' with value '691f06070b0a3a5726f6933e'. The only value found was '691f06070b0a3a5726f6933f'.
   OK: A meter with name 'mongodb.driver.commands' has a tag 'collection' with value 'testCol'.
   OK: A meter with name 'mongodb.driver.commands' has a tag 'command' with value 'dropIndexes'. 
....
```

----

IMO, we need to do two things:

1.  Allow each test to create its own mongo client instead of doing it in BeforeEach block. Therefore, we won't have tests with two client instances and avoid race conditions.
 
2. Await for the clusterId to be set before proceeding with the assertions.Basically, assertions like `assertThat(clusterId.get()).isNotNull()` can be wrapped with `Awaitlity.await().untilAssrted(...)`

If this looks ok, should I prepare a PR to fix it?

**Comment by shakuzen** [comment]
What you described sounds reasonable to me. One snag is that it looks like the code in the BeforeEach method may be used for a code snippet in documentation (see the comment tags like `// tag::setup[]`). It seems weird anyway that we have the setting of the `clusterId` in a snippet we would use in the documentation since it's purely a concern for testing. Feel free to propose something in a pull request that makes sense and we'll review. Thank you for taking the time to look into this and analyze it.

**Comment by etrandafir93** [comment]
@shakuzen I have applied the changes and tried to keep the docs intact.
Let me know what you think.
