### ISSUE TITLE
Monitor contention in environments with high cardinality identifiers

### ISSUE THREAD

**Issue by DanielThomas** [micrometer-metrics/micrometer#4629]
This very coarse lock on the `ConcurrentMap` `meterMap` can lead to excessive blocking in high RPS environment that create ids at a high rate:

https://github.com/micrometer-metrics/micrometer/blob/d6fc0b8fdcb10bd90707855b67c8d27adf83bee4/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L608-L639

From a 30 second profile of one of our applications, at around 200 rps:

<img width="981" alt="gusto-dgs-error-metric" src="https://github.com/micrometer-metrics/micrometer/assets/1479220/fdc52946-caef-4200-9109-e047635d5fa3">

**Environment**

Confirmed this is an issue at current mainline.

**To Reproduce**

Concurrently create meters with unique Ids. Note the monitor contention.

**Expected behavior**
The `MeterRegistry` should optimize for highly concurrent environments, and avoid coarse locking, particularly on the meter creation hot path.

**Comment by DanielThomas** [comment]
Experimenting with this locally, this isn't as straight forward as it first appears, because synthetic meters are recursively registered:

```
    java.lang.IllegalStateException: Recursive update
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:609)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:585)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:578)
        at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:319)
        at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:195)
        at io.micrometer.core.instrument.distribution.HistogramGauges.<init>(HistogramGauges.java:141)
        at io.micrometer.core.instrument.distribution.HistogramGauges.register(HistogramGauges.java:89)
        at io.micrometer.core.instrument.distribution.HistogramGauges.getHistogramGauges(HistogramGauges.java:53)
        at io.micrometer.core.instrument.distribution.HistogramGauges.registerWithCommonFormat(HistogramGauges.java:48)
        at io.micrometer.core.instrument.step.StepMeterRegistry.newTimer(StepMeterRegistry.java:83)
        at io.micrometer.core.instrument.MeterRegistry.lambda$timer$5(MeterRegistry.java:333)
        at io.micrometer.core.instrument.MeterRegistry.lambda$getOrCreateMeter$10(MeterRegistry.java:624)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:609)
        at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:585)
        at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:331)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:459)
        at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:453)
```

So these would have to be lifted out to avoid being recursive, and ideally, also avoid a separate locks for synthetics.

**Comment by DanielThomas** [comment]
While investigating https://github.com/micrometer-metrics/micrometer/issues/4747 I looked closer at the excessive dimensionality of the metrics for this class of service. It turns out that https://github.com/Netflix/dgs-framework/ tags internally can lead to very high numbers of distinct meters, and due to the lack of expiry, are essentially a memory leak:

```
gql.resolver: 39829
dgs.req.passport: 78941
gql.query: 6764525
```

Those dimensions are excessive even without this monitor to deal with, but lock-free atomic registration and removal of meters by key (and expiry!) would close the gap between plain Spectator and Micrometer significantly.

**Comment by shakuzen** [comment]
Thanks for taking a look at this. I think there are improvements that can be made here but it's going to take some care due to the very central nature of this code. We've tended toward being overly cautious about correctness over performance. The last relevant change in this code was probably the move off of PCollections to standard Java collections in https://github.com/micrometer-metrics/micrometer/commit/47912661796ff9ae30d9f3326c5921b65bddde5d. I'll have to spend some more time looking at the synthetic meters implementation, and maybe we can add some jcstress tests for the specific scenarios about which we want to guarantee correctness.

**Comment by tsobe** [comment]
Hey there ✋, letting you know that I also witnessed a similar problem a few months ago for a metric with 2 labels, with a cardinality of 5 and 32, respectively. They were being registered/used in the API with ~300-500 requests/sec rate. 

As a workaround, we had to switch to Otel SDK.

**Comment by shakuzen** [comment]
@tsobe I would not expect 2 tags with cardinalities of 5 and 32 to result in bad performance at 300-500 requests per second. After this issue was opened, we introduced a meter cache in 1.13.0 that largely avoids entering the synchronized block when retrieving an existing meter. The lock is now mostly only relevant for the initial meter creation. When you say a similar problem, do you mean you noticed contention on this lock or something else? I'd be interested to understand better what you were seeing.

**Comment by tsobe** [comment]
@shakuzen AFAIK, we were experiencing contention while registering metrics, even on 1.14.6. Sadly, it was a long time ago, and I don't remember the specifics.

**Comment by tsobe** [comment]
@shakuzen I just realized I forgot to mention an important detail: we were using [Ktor Micrometer integration](https://ktor.io/docs/server-metrics-micrometer.html). Most likely, it's specific to this setup.

**Comment by shakuzen** [comment]
I wonder if [KTOR-8276](https://youtrack.jetbrains.com/issue/KTOR-8276/MicrometerMetrics-different-path-404s-requests-can-be-abused-to-trigger-OOM) or [KTOR-3194](https://youtrack.jetbrains.com/issue/KTOR-3194/Override-default-http-metrics-micrometer) might explain the behavior you were seeing. The former has been fixed while the latter remains open. These high cardinality issues should be addressed in the instrumentation ideally. Perhaps the lock contention was coming from the Ktor instrumentation instead of your own meter?

**Comment by dlegaspi-ias** [comment]
this is not unique to Kotlin apps.  we are currently running into this issue now in our Java Spring Boot application.  I suppose I was under the impression that `MeterRegistry::getOrCreateMetar` is a "cheap" call 🫠 ...we are seeing this thread contention in YourKit...this kinda makes sense now.

**Comment by shakuzen** [comment]
@dlegaspi-ias `getOrCreateMeter` is a cheap call except when creating high-cardinality meters (the *create* part of *get or create*), which is generally discouraged to begin with. Is that something you're doing intentionally or unintentionally? Instrumentation provided by libraries (Micrometer itself included) generally should not create high-cardinality meters. Is it custom instrumentation in your application that's producing high-cardinality?

**Comment by javier-espinazo** [comment]
We are using the `@Timed` annotation to create timers implicitly, but we do have a custom aspect around the default one that we can control.

Our custom aspect delegates the actual micrometer integration to `reactor.core.observability.micrometer.Micrometer::metrics()`. We also have control over which dimensions and dimension values we allow - right now we're filtering metrics after they are created via `MeterFilter`.

If instead of using a `MeterFilter` we avoid calling `Micrometer::metrics()` altogether, will that improve the performance by avoiding `getOrCreateMeter()` for those meters that will be filtered out anyway?

For those that _do_ get created, do they always have to go through the `synchronized` block? The only path that I see in the code for avoiding it should log a `WARN` message of double registration that we are not seeing in our logs. The timers that we are creating have only 3 dimensions (class name, method name and a custom one that has a fixed value based on configuration) and pretty much from when the app starts serving traffic all of the combinations of those dimensions are created.
