### ISSUE TITLE
Otel Gauge setGauge() NoSuchMethodError

### ISSUE THREAD

**Issue by cyrusjk** [micrometer-metrics/micrometer#4853]
**Describe the bug**
Getting exception in spring boot using Micrometer to export to OpenTelemetry

`XX:XX:XX.XXX [otlp-metrics-publisher] WARN  i.m.c.i.push.PushMeterRegistry - Unexpected exception thrown while publishing metrics for OtlpMeterRegistry
java.lang.NoSuchMethodError: 'io.opentelemetry.proto.metrics.v1.Metric$Builder io.opentelemetry.proto.metrics.v1.Metric$Builder.setGauge(io.opentelemetry.proto.metrics.v1.Gauge$Builder)'
	at io.micrometer.registry.otlp.OtlpMeterRegistry.writeGauge(OtlpMeterRegistry.java:313)
	at io.micrometer.core.instrument.Meter.match(Meter.java:101)
	at io.micrometer.registry.otlp.OtlpMeterRegistry.lambda$publish$0(OtlpMeterRegistry.java:148)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.micrometer.registry.otlp.OtlpMeterRegistry.publish(OtlpMeterRegistry.java:151)
	at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafelyOrSkipIfInProgress(PushMeterRegistry.java:64)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`
**Environment**

Assumed relevant versions:

Spring Boot 3.2.3
io.micrometer:micrometer-registry-otlp:1.12.4
io.micrometer:micrometer-tracing-bridge-otel:1.2.4
io.opentelemetry:opentelemetry-exporter-otlp:1.36.0
io.opentelemetry:opentelemetry-proto:0.17.1

Java 17
Linux

**To Reproduce**
Occurs during expected periodic push of metrics in running container

**Expected behavior**
That a NoSuchMethodError would not be thrown

**Additional context**
This is using the "latest" versions of the available libraries, so it may just be a miss-match/race condition on update, but if there is an appropriate version of something it would be great to know.

**Comment by jonatan-ivanov** [comment]
You are using incompatible versions (at least `opentelemetry-proto`), please do not define versions on your own but use the BOM.
