### ISSUE TITLE
ERROR when use micrometer 1.0.0-1.0.2 in zipkin server with Spring Boot 1.5.3

### ISSUE THREAD

**Issue by ettwz** [micrometer-metrics/micrometer#520]
I want to use micrometer in my zipkin server project. But I received
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'zipkin.collector.CollectorMetrics' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1486)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 25 more
```
when creating bean 'zipkinMessageListener'.
BUT the version 1.0.0-rc.2 can work well. What should I do?
Spring Boot version of project is 1.5.3.RELEASE.
And Spring Cloud version is Dalston.SR4.
Thanks.

**Comment by adriancole** [comment]
this is a zipkin issue. While we don't support custom servers in zipkin, we will migrate to micrometer which is your primary concern. How about opening an issue to move to micrometer for us? https://github.com/openzipkin/zipkin

**Comment by checketts** [comment]
@adriancole Any idea why rc2 worked for @ettwz ? Did micrometer drop something we need to document, or is it a red herring?

**Comment by adriancole** [comment]
our internal metrics are still actuator metrics. I can't see a direct relationship to micrometer. The stream server which I guess is used here was dropped after 1.3.x. 

https://github.com/spring-cloud/spring-cloud-sleuth/blob/1.3.x/spring-cloud-sleuth-zipkin-stream/src/main/java/org/springframework/cloud/sleuth/zipkin/stream/EnableZipkinStreamServer.java#L41

The above project no longer exists as it is obviated by the normal zipkin server. Anyway, it "should" inherit the bean not found, just isn't. My guess this is more to do with a classpath or drift problem than micrometer.

**Comment by ettwz** [comment]
I injected a CollectorMetrics in my Application.class like this:
```java
@Bean(name = "myCollectorMetrics")
CollectorMetrics metrics(Optional<CounterBuffers> counterBuffers, Optional<GaugeBuffers> gaugeBuffers) {
	return new ActuateCollectorMetrics(counterBuffers.orElse(new CounterBuffers()),
		gaugeBuffers.orElse(new GaugeBuffers()));
}
```
zipkin and micrometer are working correctly.
looks like
```java
@ConditionalOnMissingBean(CollectorSampler.class)
```
have some problems.
Because I only find one ActuateCollectorMetrics bean in my /beans endpoint.

**Comment by adriancole** [comment]
fyi next minor of zipkin will avoid this, a later one will move to micrometer formally https://github.com/openzipkin/zipkin/pull/1975
