### ISSUE TITLE
`ClassNotFoundException` using `Counter` from Micrometer version `1.13.1`

### ISSUE THREAD

**Issue by mauricio-sky** [micrometer-metrics/micrometer#5225]
### Context

From the version `1.13.1`, using the Counter only, by default, throws an exception on runtime as follow:

<details><summary>Stack trace</summary>

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/prometheus/metrics/tracer/initializer/SpanContextSupplier
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.doSampleExemplar(ExemplarSampler.java:327)
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.updateExemplar(ExemplarSampler.java:310)
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.doObserveSingleExemplar(ExemplarSampler.java:123)
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.doObserve(ExemplarSampler.java:111)
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.lambda$observe$0(ExemplarSampler.java:99)
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.rateLimitedObserve(ExemplarSampler.java:276)
	at io.prometheus.metrics.core.exemplars.ExemplarSampler.observe(ExemplarSampler.java:99)
	at io.prometheus.metrics.core.metrics.Counter$DataPoint.inc(Counter.java:167)
	at io.prometheus.metrics.core.metrics.Counter.inc(Counter.java:53)
	at io.prometheus.metrics.core.datapoints.CounterDataPoint.inc(CounterDataPoint.java:53)
	at org.example.Main.main(Main.java:7)
Caused by: java.lang.ClassNotFoundException: io.prometheus.metrics.tracer.initializer.SpanContextSupplier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
```

</details>

### How to reproduce the issue?

1. Create a gradle project and includes the dependency:

```
    implementation("io.micrometer:micrometer-registry-prometheus:1.13.1")
```

2. Create a main method with the code below and run it:

```
import io.prometheus.metrics.core.metrics.Counter;

public class Main {
    public static void main(String[] args) {
        Counter.builder().name("test_metric").build().inc();
    }
}

```

### Alternatives to fix it

The alternatives I found to fix the issue, is 1. setting the Counter without Examples (method `.withoutExemplars()`), or import the library `io.prometheus:metrics.tracer.initializer` explicitly.

### Investigation notes

- It does not happen on `1.12.7`
- I found that the issue started with the change in the java_client 1.x on [this commit](https://github.com/prometheus/client_java/commit/966360b2735fb975a7110699efd4cb62284dfc0b)

**Comment by jonatan-ivanov** [comment]
You are not using a Micrometer `Counter` (`io.micrometer.core.instrument.Counter`) but a Prometheus `Counter` (`io.prometheus.metrics.core.metrics.Counter`) and there is nothing in your stacktrace that is from Micrometer. I'm not getting why you use the Micrometer dependency instead of Prometheus.

If you look at the code where this issue is coming from (stacktrace: [`ExemplarSampler.java:327`](https://github.com/prometheus/client_java/blob/5867b799a735288147bfd9ee680ca588a34490b9/prometheus-metrics-core/src/main/java/io/prometheus/metrics/core/exemplars/ExemplarSampler.java#L323-L327)), you will find this comment:
```java
// Using the qualified name so that Micrometer can exclude the dependency on prometheus-metrics-tracer-initializer
// as they provide their own implementation of SpanContextSupplier.
// If we had an import statement for SpanContextSupplier the dependency would be needed in any case.
SpanContext spanContext = this.spanContext != null ? this.spanContext : io.prometheus.metrics.tracer.initializer.SpanContextSupplier.getSpanContext();
``` 

As the comment implies, Micrometer intentionally [excludes](https://github.com/micrometer-metrics/micrometer/blob/b0386c8e6958ac37da5537960e167777da4f4c31/implementations/micrometer-registry-prometheus/build.gradle#L6-L10) `prometheus-metrics-tracer-initializer`. This is because of dependency hygiene: you might not need `prometheus-metrics-tracer-otel` and `prometheus-metrics-tracer-otel-agent` that `prometheus-metrics-tracer-initializer` [brings in](https://repo1.maven.org/maven2/io/prometheus/prometheus-metrics-tracer-initializer/1.3.1/prometheus-metrics-tracer-initializer-1.3.1.pom).

So you need to decide if you want to use the Prometheus `Counter` in which case you should use the Prometheus dependencies not Micrometer or the Micrometer `Counter` in which case you should use the Micrometer dependencies. In the case you want to use both (I don't recommend it) either you need to disable exemplars support in Prometheus or add `io.prometheus:metrics.tracer.initializer`.
