### ISSUE TITLE
Common tags are killing http_server_requests

### ISSUE THREAD

**Issue by Eloo** [micrometer-metrics/micrometer#59]
When I apply common tags to a prometheus registry the http_server_requests metrics get "killed".
More precise the textwriter for format004 throws an index out of bound exception.
This issue occurs the first time after the very first request against a timed endpoint was made.

```
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[na:1.8.0_131]
	at java.util.LinkedList.get(LinkedList.java:476) ~[na:1.8.0_131]
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:42) ~[simpleclient_common-0.0.25.jar:na]
	at io.micrometer.spring.export.prometheus.PrometheusActuatorEndpoint.invoke(PrometheusActuatorEndpoint.java:48) ~[micrometer-spring-legacy-0.7.0.RELEASE.jar:0.7.0.RELEASE]
```

The tags are set like this
```
    @Autowired
    private PrometheusMeterRegistry prometheusMeterRegistry;

    @PostConstruct
    public void setCommonTags() {
        prometheusMeterRegistry.commonTags("stack", "prod", "region", "us-east-1");
    }
```

thanks

**Comment by Eloo** [comment]
It seems that the values are not added correctly
![screen shot 2017-07-26 at 10 09 23](https://user-images.githubusercontent.com/2631895/28611021-b19c5c74-71ea-11e7-915b-2418ffeaff72.png)

**Comment by Eloo** [comment]
yep seems to work ;)
thanks a lot
