### ISSUE TITLE
Incorrect number of labels when binding JvmMemoryMetrics and use common Tags

### ISSUE THREAD

**Issue by Eloo** [micrometer-metrics/micrometer#67]
If you bind the JvmMemoryMetrics and use common tags the application will no longer start.
I know the JvmMemoryMetrics are already bind per default but nevertheless i guess the exception shouldn't be thrown.

Example:
```
 @Autowired
    private MeterRegistry registry;

    public static void main() {
        SpringApplication.run(TestApplication.class);
    }

    @Bean
    public MeterRegistryConfigurer configurer() {
        return registry -> registry.commonTags("region", "test");
    }

    @PostConstruct
    public void registerBinders() {
        new JvmMemoryMetrics().bindTo(registry);
    }
```
Exception:
```
Caused by:
            java.lang.IllegalArgumentException: Incorrect number of labels.
                at io.prometheus.client.SimpleCollector.setChild(SimpleCollector.java:135)
                at io.micrometer.core.instrument.prometheus.PrometheusMeterRegistry.lambda$gauge$14(PrometheusMeterRegistry.java:174)
                at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
                at io.micrometer.core.instrument.util.MapAccess.computeIfAbsent(MapAccess.java:36)
                at io.micrometer.core.instrument.prometheus.PrometheusMeterRegistry.gauge(PrometheusMeterRegistry.java:160)
                at io.micrometer.core.instrument.binder.JvmMemoryMetrics.bindTo(JvmMemoryMetrics.java:40)
                at io.micrometer.spring.MeterRegistryConfigurationSupport.lambda$bindAll$1(MeterRegistryConfigurationSupport.java:52)
```

**Comment by Eloo** [comment]
further i figured out with the above implemenation the commonTags are not added to every metricbinder.
but the following works
```
 @Bean
    public MeterRegistryConfigurer addCommonTags() {
        return registry -> {
            registry.commonTags("region", "test");
        };
    }

    @Bean
    public MeterRegistryConfigurer bindMetrics() {
        return registry -> {
            new ClassLoaderMetrics().bindTo(registry);
            new JvmGcMetrics().bindTo(registry);
            new ProcessorMetrics().bindTo(registry);
            new ThreadMetrics().bindTo(registry);
        };
    }
```

is this the intended usage?

**Comment by jkschneider** [comment]
This is not the intended usage. Evidently there is some more work to do to enforce the ordering of the configurers before binders.

**Comment by Eloo** [comment]
okay, so what is the best practice to bind for example the ProcessorMetrics binder?

**Comment by jkschneider** [comment]
The idea is you should be able to just register a @Bean of type `ProcessorMetrics`.

**Comment by jkschneider** [comment]
I could see having an additional hook in the `MeterRegistryConfigurer` might be nice for when you want to register a bunch of them.

**Comment by jkschneider** [comment]
Here's the deal: `@PostConstruct` is evaluated before `@Bean`, so there's no way we can enforce the application of a `MeterRegistryConfigurer` before the binder is created. Any of the following 3 approaches are acceptable:

## Using `@PostConstruct`

```java
@Autowired MeterRegistry registry;

@PostConstruct
public void jvmMetrics() {
    registry.commonTags("region", "test");
    new JvmMemoryMetrics().bindTo(registry);
}
```

## Using `MeterRegistryConfigurer` and wiring the binder as a `@Bean`

```java
@Bean JvmMemoryMetrics memoryMetrics() { 
    return new JvmMemoryMetrics(); // this is automatically bound to your registry
} 

@Bean MeterRegistryConfigurer configurer() {
    return registry -> registry.commonTags("region", "test");
}
```

## Using `MeterRegistryConfigurer` exclusively

```java
@Bean MeterRegistryConfigurer configurer() {
    return registry -> {
        registry.commonTags("region", "test");
        new JvmMemoryMetrics().bindTo(registry);
    }
}
```
