### ISSUE TITLE
Deadlock caused by infinite loop and  ConcurrentModificationException exception

### ISSUE THREAD

**Issue by jvmlet** [micrometer-metrics/micrometer#704]
Hello 
I'm experiencing 2  concurrency issues when integration the micrometer using `micrometer-spring-legacy` module.

My main spring boot application  launches several `embedded` spring boot applications (actually these are  the `spring-task` app that auto-closes it's context) :

````java
public void someAsyncEventHandler(){
 new SpringApplicationBuilder()
                    .sources(EmbeddedTaskApp.class)
                    .run();
}
````
The `EmbeddedTaskApp.class` autowires the `   @Autowired    private  MeterRegistry meterRegistry;`

After few invocations of   `someAsyncEventHandler` , the below `for(;;)` loop never ends (from `CompositeMeterRegistry` class ) :
````java
    void updateDescendants(boolean lock) {
        Set<MeterRegistry> descendants = Collections.newSetFromMap(new IdentityHashMap<>());
        for (; ; ) { //  !!! INFINITE LOOP CAUSED BY NEXT IF STATEMENT 
            if (registriesLock.compareAndSet(!lock, true)) { // THIS NEVER RETURNS TRUE !!!
               ......
           }
       }
}
````
Another exception I'm getting sometimes is this one :

````
o.s.boot.SpringApplication               : Application startup failed java.util.ConcurrentModificationException: null
    at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:735)
      at java.util.IdentityHashMap$KeyIterator.next(IdentityHashMap.java:826)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.updateDescendants(CompositeMeterRegistry.java:188)
  at io.micrometer.core.instrument.composite.CompositeMeterRegistry.add(CompositeMeterRegistry.java:140)
        at io.micrometer.core.instrument.Metrics.addRegistry(Metrics.java:44)
  at io.micrometer.spring.autoconfigure.MeterRegistryConfigurer.configure(MeterRegistryConfigurer.java:61)
      at io.micrometer.spring.autoconfigure.MeterRegistryPostProcessor.postProcessAfterInitialization(MeterRegistryPostProcessor.java:47)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1634)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
     ... 29 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMeterRegistry' defined in class path resource [io/micrometer/spring/autoconfigure/export/simple/SimpleMetricsExportAutoConfiguration.class]: Initialization of bean failed; nested exception is java.util.ConcurrentModificationException
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
      at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
 at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
      at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
       at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
      ... 20 common frames omitted
Wrapped by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'taskRunner': Unsatisfied dependency expressed through field 'meterRegistry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMeterRegistry' defined in class path resource [io/micrometer/spring/autoconfigure/export/simple/SimpleMetricsExportAutoConfiguration.class]: Initialization of bean failed; nested exception is java.util.ConcurrentModificationException
  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
      at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
   at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
       at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
       at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
 at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
   at com.mycompany.embeddedEtlTask.run(EmbeddedEtlTask.java:79)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
````

**Comment by jkschneider** [comment]
Thanks for the detailed report @jvmlet!
