### ISSUE TITLE
Handle infinity values (-∞)

### ISSUE THREAD

**Issue by mveitas** [micrometer-metrics/micrometer#778]
Our team recently started to publish some metrics from Kafka client using the provided `MetricsReporter` and sending them to Dogstatsd. Some of the values being reported are being translated into non-numeric values: `-∞`.

One possible suggestion is to assign the values of negative and positive infinity into min and max double value respectively by overriding `DatadogStatsdLineBuilder`

``` 
    @Override
    public String gauge(double amount, Statistic stat) {
        if (amount == Double.NEGATIVE_INFINITY) {
            amount = Double.MIN_VALUE;
        } else if (amount == Double.POSITIVE_INFINITY) {
            amount = Double.MAX_VALUE;
        }

        return super.gauge(amount, stat);
    }
```

Before submitting a PR, I wanted to see if there was any issues that you might see with the above.

Below is an example of the error seen in syslog from Dogstatsd
`
Aug  2 17:53:59 localhost dd.dogstatsd[8618]: ERROR (dogstatsd.py:451): Error receiving datagram `kafka.client.consumer-node-metrics.request-latency-max:-∞|g|#statistic:value,client-id:consumer-3,node-id:node--2`#012Traceback (most recent call last):#012  File "/opt/datadog-agent/agent/dogstatsd.py", line 439, in start#012    aggregator_submit(message)#012  File "/opt/datadog-agent/agent/aggregator.py", line 620, in submit_packets#012    parsed_packets = self.parse_metric_packet(packet)#012  File "/opt/datadog-agent/agent/aggregator.py", line 492, in parse_metric_packet#012    raise Exception(u'Metric value must be a number: %s, %s' % (name, raw_value))#012UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
`

**Comment by mveitas** [comment]
@jkschneider Curious if you had any feedback about this?
