### ISSUE TITLE
registry.timer(..) registers `null` base time unit

### ISSUE THREAD

**Issue by JigarJoshi** [micrometer-metrics/micrometer#822]
```
Timer timer = registry.timer("testTimer", Tags.empty());
````

This code throws `NullPointerException` in `1.0.6` release.
This is due to `io.micrometer.core.instrument.Timer.Builder#register` passes `null` as `baseUnit`  and then later`io.micrometer.core.instrument.MeterRegistry#timer(io.micrometer.core.instrument.Meter.Id, io.micrometer.core.instrument.distribution.DistributionStatisticConfig, io.micrometer.core.instrument.distribution.pause.PauseDetector)`  calls 
```
Meter.Id withUnit = id2.withBaseUnit(getBaseTimeUnitStr());
```

Stacktrace

```
Exception in thread "main" java.lang.NullPointerException
	at io.micrometer.core.instrument.MeterRegistry.getBaseTimeUnitStr(MeterRegistry.java:221)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:256)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:566)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:528)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:255)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:447)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:382)
```

**Comment by izeye** [comment]
@JigarJoshi It shouldn't happen with a non-null contract on `MeterRegistry.getBaseTimeUnit()`. See https://github.com/micrometer-metrics/micrometer/blob/v1.0.6/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L202-L205

I checked all `MeterRegistry.getBaseTimeUnit()` implementations in the `1.0.x` branch and there is nothing which breaks the contract. So it doesn't seem to be possible unless you're using your own `MeterRegistry` implementation which breaks the contract. Could you give me more info on your setup to reproduce the issue?

**Comment by JigarJoshi** [comment]
That is correct, I had it unimplemented in registry.
