### ISSUE TITLE
Metrics are reported even though they are disabled

### ISSUE THREAD

**Issue by Edholm** [micrometer-metrics/micrometer#861]
I have disabled metrics in some environments (tests for example), but they are still reported once when the application is being shut down.

```
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_181]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_181]
	at java.net.Socket.<init>(Socket.java:244) ~[na:1.8.0_181]
	at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277) ~[na:1.8.0_181]
	at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:126) ~[metrics-graphite-3.2.6.jar:3.2.6]
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:240) ~[metrics-graphite-3.2.6.jar:3.2.6]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:243) [metrics-core-3.2.6.jar:3.2.6]
	at io.micrometer.graphite.GraphiteMeterRegistry.close(GraphiteMeterRegistry.java:90) [micrometer-registry-graphite-1.0.6.jar:1.0.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:337) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1041) [spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1017) [spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:937) [spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
```

This issue looks to be due to `close()` being called in `GraphiteMeterRegistry` and that in turn calls `this.reporter.report()` even though the reporter never having been started in the first place.

For me this doesn't break anything, it just results in an ugly stacktrace when running integration tests for example.

Running the following versions:
* spring-boot 2.0.5.RELEASE
* spring-boot-starter-actuator 2.0.5.RELEASE
* micrometer-registry-graphite 1.0.6

**Comment by izeye** [comment]
@Edholm Thanks for the report! It does seem you're right. I can see the inconsistency handling `this.report` with `this.config.enabled()`. I created #863 to resolve it.
