### ISSUE TITLE
NewRelicRegistry is failing behind proxy

### ISSUE THREAD

**Issue by pulkitmehra** [micrometer-metrics/micrometer#995]
micrometer version: 1.1.0
Spring boot: 2.0.6

I am trying to push data to newrelic. We are behind a proxy and I am setting following env variable during spring boot start up
-Dhttp.proxyHost=
-Dhttp.proxyPort=

But the push is failing everytime time. It's saying 

``` NewRelicMeterRegistry [{}]: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at io.micrometer.core.ipc.http.HttpUrlConnectionSender.send(HttpUrlConnectionSender.java:55)
	at io.micrometer.core.ipc.http.HttpSender$Request$Builder.send(HttpSender.java:284)
	at io.micrometer.newrelic.NewRelicMeterRegistry.sendEvents(NewRelicMeterRegistry.java:212)
	at io.micrometer.newrelic.NewRelicMeterRegistry.publish(NewRelicMeterRegistry.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
failed to send metrics to new relic```

Is there way I can specify proxy settings in `HttpSender` client explicitly?

**Comment by jkschneider** [comment]
@pulkitmehra You can also programmatically inject your own `HttpSender` so you don't have to add props to your app run. Supply your own or extend one of the existing `HttpSender` implementations to do whatever magic you have to do to deal with networking.

**Comment by pulkitmehra** [comment]
@jkschneider , thank you for letting us know. I'll definitely try that route!
